[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "python -m spacy download id_core_news_sm || true",
  "python -m spacy download xx_ent_wiki_sm || true",
  "python -m nltk.downloader vader_lexicon stopwords || true"
]

[start]
cmd = "uvicorn api.main:app --host 0.0.0.0 --port $PORT"
