import type { BarDataPoint } from "./svg-utils"

export const UMP_BY_PROVINCE: BarDataPoint[] = [
  { label: "DKI Jakarta",    value: 5.40 },
  { label: "Papua Selatan",  value: 4.29 },
  { label: "Papua Barat",    value: 3.97 },
  { label: "Sulawesi Utara", value: 3.68 },
  { label: "Babel",          value: 3.67 },
  { label: "Aceh",           value: 3.60 },
  { label: "Kaltim",         value: 3.58 },
  { label: "Kaltara",        value: 3.58 },
  { label: "Sulawesi Sel.",  value: 3.43 },
  { label: "Kepri",          value: 3.45 },
  { label: "Kalsel",         value: 3.49 },
  { label: "Kalteng",        value: 3.47 },
  { label: "Sumatera Sel.",  value: 3.31 },
  { label: "Riau",           value: 3.29 },
  { label: "Maluku Utara",   value: 3.20 },
  { label: "Jambi",          value: 3.22 },
  { label: "Sulawesi Tra.",  value: 3.07 },
  { label: "Maluku",         value: 3.05 },
  { label: "Sulawesi Bar.",  value: 3.03 },
  { label: "Gorontalo",      value: 2.99 },
  { label: "Sumatera Bar.",  value: 2.99 },
  { label: "Sulawesi Ten.",  value: 2.91 },
  { label: "Kalbar",         value: 2.94 },
  { label: "Lampung",        value: 2.89 },
  { label: "Bali",           value: 2.81 },
  { label: "Sumatera Utara", value: 2.81 },
  { label: "Banten",         value: 2.73 },
  { label: "NTB",            value: 2.64 },
  { label: "Bengkulu",       value: 2.61 },
  { label: "NTT",            value: 2.32 },
  { label: "DIY",            value: 2.24 },
  { label: "Jawa Timur",     value: 2.17 },
  { label: "Jawa Tengah",    value: 2.17 },
  { label: "Jawa Barat",     value: 2.09 },
].sort((a, b) => b.value - a.value)

export const INF_BY_CATEGORY: { label: string; v2024: number; v2025: number }[] = [
  { label: "Perawatan Pribadi", v2024: 7.02, v2025: 13.33 },
  { label: "Restoran",          v2024: 2.48, v2025: 1.46 },
  { label: "Pendidikan",        v2024: 1.94, v2025: 1.22 },
  { label: "Kesehatan",         v2024: 1.93, v2025: 1.83 },
  { label: "Makanan & Minum",   v2024: 1.90, v2025: 4.58 },
  { label: "Rekreasi",          v2024: 1.17, v2025: 1.17 },
  { label: "Umum",              v2024: 1.57, v2025: 2.92 },
  { label: "Perabot RT",        v2024: 1.04, v2025: 0.20 },
  { label: "Pakaian",           v2024: 1.16, v2025: 0.66 },
  { label: "Perumahan",         v2024: 0.59, v2025: 1.62 },
  { label: "Transportasi",      v2024: -0.30, v2025: 1.23 },
  { label: "Info & Komuni.",    v2024: -0.27, v2025: -0.28 },
]

export const TPT_BY_PROVINCE: BarDataPoint[] = [
  { label: "Papua",            value: 6.96 },
  { label: "Maluku",           value: 6.41 },
  { label: "Sulawesi Utara",   value: 6.13 },
  { label: "Kep. Riau",        value: 6.02 },
  { label: "Jawa Barat",       value: 5.83 },
  { label: "Aceh",             value: 5.78 },
  { label: "Maluku Utara",     value: 5.65 },
  { label: "DKI Jakarta",      value: 5.59 },
  { label: "Banten",           value: 5.42 },
  { label: "Kalimantan Timur", value: 5.24 },
  { label: "Sulawesi Barat",   value: 5.13 },
  { label: "Sulawesi Tenggara",value: 4.91 },
  { label: "NTT",              value: 4.64 },
  { label: "Sumatra Utara",    value: 4.60 },
  { label: "Gorontalo",        value: 4.57 },
  { label: "Papua Barat",      value: 4.51 },
  { label: "Kep. Bangka Bel.", value: 4.42 },
  { label: "Sulawesi Selatan", value: 4.34 },
  { label: "Riau",             value: 4.21 },
  { label: "Kalimantan Utara", value: 4.11 },
  { label: "Sulawesi Tengah",  value: 3.98 },
  { label: "Kalimantan Barat", value: 3.87 },
  { label: "Kalimantan Sel.",  value: 3.79 },
  { label: "Jambi",            value: 3.74 },
  { label: "Sumatra Selatan",  value: 3.65 },
  { label: "Jawa Timur",       value: 3.61 },
  { label: "Bengkulu",         value: 3.57 },
  { label: "NTB",              value: 3.53 },
  { label: "Sumatra Barat",    value: 3.49 },
  { label: "Lampung",          value: 3.40 },
  { label: "Jawa Tengah",      value: 3.22 },
  { label: "Bali",             value: 1.49 },
]

export const HAPPINESS_BY_PROVINCE: BarDataPoint[] = [
  { label: "Maluku Utara",    value: 76.34 },
  { label: "Kaltara",         value: 75.98 },
  { label: "Kaltim",          value: 75.72 },
  { label: "Gorontalo",       value: 75.41 },
  { label: "Sulawesi Utara",  value: 75.36 },
  { label: "Maluku",          value: 74.88 },
  { label: "Papua Barat",     value: 74.63 },
  { label: "Kalimantan Sel.", value: 74.42 },
  { label: "Sulawesi Sel.",   value: 74.17 },
  { label: "Bangka Belitung", value: 73.91 },
  { label: "Sulawesi Tengah", value: 73.65 },
  { label: "NTT",             value: 73.44 },
  { label: "Jambi",           value: 73.28 },
  { label: "Bali",            value: 73.14 },
  { label: "DIY",             value: 72.86 },
  { label: "DKI Jakarta",     value: 71.57 },
  { label: "Jawa Timur",      value: 70.93 },
  { label: "Jawa Barat",      value: 70.12 },
  { label: "Jawa Tengah",     value: 69.44 },
  { label: "Banten",          value: 68.08 },
].sort((a, b) => b.value - a.value)

export const INTERNET_BY_PROVINCE: BarDataPoint[] = [
  { label: "Kep. Riau",       value: 98.41 },
  { label: "DKI Jakarta",     value: 97.83 },
  { label: "DI Yogyakarta",   value: 96.52 },
  { label: "Bali",            value: 95.74 },
  { label: "Kalimantan Tim.", value: 95.31 },
  { label: "Bangka Belitung", value: 94.87 },
  { label: "Sulawesi Utara",  value: 94.22 },
  { label: "Riau",            value: 93.65 },
  { label: "Banten",          value: 93.41 },
  { label: "Jawa Barat",      value: 93.18 },
  { label: "Jawa Timur",      value: 92.74 },
  { label: "Kaltara",         value: 92.43 },
  { label: "Jawa Tengah",     value: 91.87 },
  { label: "Sumatera Utara",  value: 91.44 },
  { label: "Sumatera Bar.",   value: 90.83 },
  { label: "Sumatera Sel.",   value: 89.67 },
  { label: "Maluku Utara",    value: 88.95 },
  { label: "Kalsel",          value: 88.54 },
  { label: "Lampung",         value: 87.92 },
  { label: "Aceh",            value: 87.45 },
  { label: "Gorontalo",       value: 86.31 },
  { label: "Jambi",           value: 86.14 },
  { label: "Sulawesi Sel.",   value: 85.73 },
  { label: "Bengkulu",        value: 84.62 },
  { label: "Kalimantan Bar.", value: 83.91 },
  { label: "Sulawesi Teng.",  value: 83.47 },
  { label: "NTB",             value: 82.83 },
  { label: "Maluku",          value: 81.26 },
  { label: "Sulawesi Tra.",   value: 80.54 },
  { label: "Sulawesi Bar.",   value: 79.31 },
  { label: "Kalteng",         value: 78.94 },
  { label: "NTT",             value: 72.18 },
  { label: "Papua Barat",     value: 61.43 },
  { label: "Papua",           value: 47.82 },
  { label: "Papua Pegunungan",value: 26.61 },
].sort((a, b) => b.value - a.value)

export const FDI_BY_COUNTRY: BarDataPoint[] = [
  { label: "Singapura",  value: 17407 },
  { label: "Hong Kong",  value: 10646 },
  { label: "China",      value: 7507 },
  { label: "Jepang",     value: 3129 },
  { label: "Korea Sel.", value: 1984 },
  { label: "USA",        value: 2974 },
  { label: "Belanda",    value: 1103 },
  { label: "Australia",  value: 719 },
].sort((a, b) => b.value - a.value)

export interface WagePoint { sector: string; age: string; wage: number }
export const WAGE_BY_AGE: WagePoint[] = [
  { sector: "Pertambangan",  age: "15-19", wage: 2.1 },
  { sector: "Pertambangan",  age: "20-24", wage: 3.4 },
  { sector: "Pertambangan",  age: "25-29", wage: 4.8 },
  { sector: "Pertambangan",  age: "30-34", wage: 5.9 },
  { sector: "Pertambangan",  age: "35-44", wage: 6.7 },
  { sector: "Pertambangan",  age: "45-54", wage: 6.2 },
  { sector: "Manufaktur",    age: "15-19", wage: 1.8 },
  { sector: "Manufaktur",    age: "20-24", wage: 2.9 },
  { sector: "Manufaktur",    age: "25-29", wage: 3.7 },
  { sector: "Manufaktur",    age: "30-34", wage: 4.2 },
  { sector: "Manufaktur",    age: "35-44", wage: 4.8 },
  { sector: "Manufaktur",    age: "45-54", wage: 4.4 },
  { sector: "Listrik & Gas", age: "15-19", wage: 2.4 },
  { sector: "Listrik & Gas", age: "20-24", wage: 3.8 },
  { sector: "Listrik & Gas", age: "25-29", wage: 5.1 },
  { sector: "Listrik & Gas", age: "30-34", wage: 6.3 },
  { sector: "Listrik & Gas", age: "35-44", wage: 7.2 },
  { sector: "Listrik & Gas", age: "45-54", wage: 6.9 },
  { sector: "Pertanian",     age: "15-19", wage: 1.2 },
  { sector: "Pertanian",     age: "20-24", wage: 1.7 },
  { sector: "Pertanian",     age: "25-29", wage: 2.1 },
  { sector: "Pertanian",     age: "30-34", wage: 2.4 },
  { sector: "Pertanian",     age: "35-44", wage: 2.6 },
  { sector: "Pertanian",     age: "45-54", wage: 2.3 },
]

export interface RicePrice { year: number; jakarta: number; banjarmasin: number; makassar: number; jayapura: number }
export const RICE_PRICES: RicePrice[] = [
  { year: 2022, jakarta: 12500, banjarmasin: 11800, makassar: 11200, jayapura: 14800 },
  { year: 2023, jakarta: 13200, banjarmasin: 12500, makassar: 11900, jayapura: 16200 },
  { year: 2024, jakarta: 15400, banjarmasin: 14100, makassar: 13600, jayapura: 18900 },
  { year: 2025, jakarta: 16100, banjarmasin: 14800, makassar: 14200, jayapura: 19800 },
]

export const GDP_BY_SECTOR: BarDataPoint[] = [
  { label: "Industri Pengolahan", value: 19.42 },
  { label: "Pertanian",           value: 13.67 },
  { label: "Perdagangan",         value: 12.98 },
  { label: "Konstruksi",          value: 9.74 },
  { label: "Pertambangan",        value: 8.47 },
  { label: "Transportasi",        value: 6.23 },
  { label: "Info & Komunikasi",   value: 5.18 },
  { label: "Keuangan & Asuransi", value: 4.89 },
  { label: "Real Estat",          value: 4.57 },
  { label: "Pemerintahan",        value: 3.96 },
  { label: "Jasa Pendidikan",     value: 3.42 },
  { label: "Lainnya",             value: 7.47 },
]
