import type { ProdiEntry } from "./types"

export const PRODI_DATA: ProdiEntry[] = [
  // === EKONOMI & BISNIS === (16)
  {
    id: "manajemen", name: "Manajemen", faculty: "Ekonomi & Bisnis",
    keywords: ["manajemen strategi","kepemimpinan organisasi","MSDM","pemasaran digital","keuangan korporat","supply chain","manajemen risiko","etika bisnis","kewirausahaan","balanced scorecard","OKR framework","manajemen proyek","negosiasi bisnis","brand strategy","customer journey","growth hacking","ESG investing","AI dalam bisnis","startup equity","Series A funding","business model canvas","SWOT analysis","KPI dashboard","agile management","change management","merger akuisisi","family business","UMKM scaling","corporate governance","manajemen hybrid","digital transformation leadership","organizational learning","blue ocean strategy","disruptive innovation","platform strategy","stakeholder capitalism","sustainable business model","data-driven management","AI for managers","robotic process automation","remote team leadership","wellness karyawan","generasi Z management","circular economy bisnis","corporate culture","innovation portfolio","business ecosystem","corporate social impact","ESG framework","scenario planning"]
  },
  {
    id: "akuntansi", name: "Akuntansi", faculty: "Ekonomi & Bisnis",
    keywords: ["laporan keuangan","audit eksternal","perpajakan","akuntansi biaya","IFRS","SAK ETAP","forensic accounting","internal control","due diligence","transfer pricing","blockchain accounting","AI audit","sustainability reporting","ESG disclosure","carbon accounting","fraud detection","coretax DJP","Sarbanes-Oxley","big four auditor","CPA certification","ACCA","CMA","akuntansi pemerintahan","laporan BPK","audit KAP","pajak penghasilan","PPN","bea masuk","akuntansi UMKM","laporan konsolidasi","PSAK 71 instrumen keuangan","PSAK 72 pendapatan","PSAK 73 sewa","SAK EMKM UMKM","earnings management","akuntansi publik daerah","digital audit tools","automated reconciliation","cloud accounting Xero","software Accurate Indonesia","AI dalam audit","continuous auditing","real-time reporting","integrated reporting IR","XBRL pelaporan","goodwill impairment","deferred tax","cash flow analysis","working capital management","analisis rasio keuangan"]
  },
  {
    id: "ekonomi-pembangunan", name: "Ekonomi Pembangunan", faculty: "Ekonomi & Bisnis",
    keywords: ["pertumbuhan ekonomi","pembangunan berkelanjutan","SDGs Indonesia","kemiskinan absolut","indeks pembangunan manusia","APBN analisis","fiskal transfer daerah","infrastruktur dan pertumbuhan","ekonomi digital Indonesia","bonus demografi","program bansos","ketimpangan Gini","investasi asing FDI","neraca pembayaran","utang luar negeri","kredit perbankan","inflasi pangan","harga BBM subsidi","transisi energi","industrialisasi","ekonomi hijau","BRICS membership","deindustrialisasi","proteksi industri","rezim devisa","middle income trap","productive complexity","otonomi daerah","Dana Desa","export-led growth","total factor productivity","human capital theory","institutional economics","state capacity","Flying Geese theory","urbanisasi ekonomi","agglomeration effects","spatial econometrics","kemiskinan multi dimensi","cash transfer evaluasi","universal basic income","digital economy","platform economy regulasi","fintech inklusi keuangan","climate finance","carbon pricing","poverty trap","demographic dividend","regional inequality","development economics"]
  },
  {
    id: "ilmu-ekonomi", name: "Ilmu Ekonomi", faculty: "Ekonomi & Bisnis",
    keywords: ["mikroekonomi","makroekonomi","ekonometrika","teori permainan","ekonomi perilaku","kebijakan moneter","suku bunga BI","inflasi target","kurva Phillips","IS-LM model","Keynes vs Friedman","teori perdagangan","comparative advantage","market failure","eksternalitas","public goods","mekanisme pasar","behavioral economics","experimental economics","ekonomi institusional","neoklasik","welfare economics","Arrow impossibility","game theory Nash","Pareto optimal","Edgeworth box","general equilibrium","new institutional economics","transaction costs","public choice theory","political economy","mechanism design","auction theory","matching theory Roth","complexity economics","evolutionary economics","post-Keynesian","modern monetary theory","environmental economics","carbon externality","Pigouvian tax","Coase theorem","nudge theory Thaler","behavioral finance","prospect theory Kahneman","bounded rationality","information asymmetry","adverse selection","moral hazard","market microstructure"]
  },
  {
    id: "bisnis-digital", name: "Bisnis Digital", faculty: "Ekonomi & Bisnis",
    keywords: ["e-commerce strategy","marketplace Indonesia","platform economy","digital transformation","fintech ekosistem","super app","data monetization","subscription model","freemium","SaaS B2B","API economy","digital payments","QRIS adoption","open banking","embedded finance","user acquisition cost","lifetime value","churn rate","conversion funnel","A/B testing","SEO organik","social commerce","TikTok shop","live commerce","AI personalisasi","recommendation engine","logistics tech","last mile delivery","omnichannel","digital supply chain","creator economy","token economy","NFT marketplace","metaverse commerce","Web3 bisnis","DAO decentralized organization","DeFi protokol","blockchain smart contract","tokenization aset","conversational commerce","voice commerce","video commerce","shoppable video","social selling","community-led growth","product-led growth","viral loop mechanism","network effects flywheel","platform liquidity","digital business model"]
  },
  {
    id: "keuangan-perbankan", name: "Keuangan & Perbankan", faculty: "Ekonomi & Bisnis",
    keywords: ["manajemen portofolio","CAPM model","valuation DCF","risk management","Basel III","POJK regulasi","perbankan syariah","reksa dana","obligasi pemerintah","saham blue chip","IPO Indonesia","rights issue","private equity","venture capital","hedging derivatif","forex risk","credit scoring","NPL rasio","CAR modal","LDR likuiditas","BPRS mikro","koperasi kredit","pinjol regulasi","fintech lending","payment gateway","SWIFT transfer","nostro vostro","correspondent banking","digital banking","neobank","CBDC bank sentral digital","open banking API","BaaS banking as service","crypto regulation","stablecoin","DeFi yield farming","robo-advisor","ETF passive investing","factor investing","ESG investing","climate risk banking","green bond","sustainable finance","Basel IV implementation","deposit insurance","systemic risk analysis","LIBOR SOFR transition","Islamic finance sukuk","wealth management","financial planning"]
  },
  {
    id: "manajemen-pemasaran", name: "Manajemen Pemasaran", faculty: "Ekonomi & Bisnis",
    keywords: ["marketing mix 4P","consumer behavior","brand equity","positioning strategi","segmentasi pasar","digital marketing","content marketing","influencer marketing","KOL Indonesia","social media ads","Meta Ads","Google Ads","programmatic advertising","customer retention","NPS score","CRM sistem","salesforce automation","viral marketing","word of mouth","neuromarketing","ethnographic research","focus group","conjoint analysis","price elasticity","promotion ROI","trade marketing","retail audit","category management","shopper marketing","omnichannel retail","growth marketing","AARRR pirate metrics","referral program","affiliate marketing","marketplace SEO","app store optimization","email automation drip","lead scoring","marketing automation","customer data platform CDP","zero party data","cookieless future","contextual advertising","creator collaboration brand","nano micro influencer","UGC user generated content","community marketing","product-led growth","brand activism","purpose-driven marketing"]
  },
  {
    id: "perpajakan", name: "Perpajakan", faculty: "Ekonomi & Bisnis",
    keywords: ["PPh badan","PPh orang pribadi","PPN mekanisme","bea masuk","pajak daerah","tax treaty","BEPS OECD","transfer pricing doc","controlled transaction","arm's length principle","pajak digital","Pillar One Two","CFC rules","thin capitalization","debt equity swap","tax amnesty","program PPS","SPT tahunan","e-filing","coretax system","PTKP terbaru","PPh 21 karyawan","PPh 23 jasa","PPh 26 luar negeri","objek pajak PPn","faktur pajak","sengketa pajak","pengadilan pajak","PKKU","advance pricing agreement","global minimum tax","crypto tax","pajak karbon Indonesia","CBAM carbon border","tax expenditure analysis","insentif tax holiday","SEZ KEK pajak","estate wealth tax","capital gain tax","anti-avoidance GAAR","economic substance rules","nexus digital economy","OECD model convention","withholding tax","permanent establishment","beneficial owner","tax risk management","pajak UMKM PP 55","e-commerce tax regulation","penegakan pajak digital"]
  },
  {
    id: "aktuaria", name: "Aktuaria", faculty: "Ekonomi & Bisnis",
    keywords: ["ilmu aktuaria","asuransi jiwa","asuransi kesehatan","mortality table","life expectancy","premium calculation","reserve asuransi","risk pooling","reinsurance","solvency margin","PSAK 74 IFRS 17","liability adequacy","catastrophe modeling","parametric insurance","climate risk","longevity risk","pandemic modeling","stochastic modeling","survival function","hazard rate","Gompertz model","pension fund","iuran pensiun","BPJS Ketenagakerjaan","BPJS Kesehatan","defisit JKN","dana pensiun syariah","financial mathematics","interest rate risk","ERM enterprise risk","IFRS 17 implementasi","ORSA internal assessment","stress testing insurance","cyber risk quantification","operational risk insurance","microinsurance","parametric crop insurance","embedded insurance fintech","InsurTech startup","peer-to-peer insurance","usage-based insurance UBI","telematics asuransi","predictive analytics claims","machine learning underwriting","NLP claims processing","open insurance API","digital distribution insurance","actuarial analytics Python R","reserving IBNR","solvency II SCR"]
  },
  {
    id: "ekonomi-islam", name: "Ekonomi Islam", faculty: "Ekonomi & Bisnis",
    keywords: ["prinsip syariah","riba dalam Islam","bagi hasil mudharabah","musyarakah","murabahah","ijarah","sukuk obligasi","perbankan syariah","takaful","zakat produktif","wakaf produktif","BAZNAS","Maqashid syariah","fiqh muamalah","DSN MUI fatwa","OJK syariah","halal supply chain","halal certification","Islamic fintech","robo advisor syariah","crowdfunding syariah","peer to peer syariah","Green sukuk","blended finance","social finance","impact investing","waqf endowment","Islamic microfinance","pasar modal syariah","JII70","fintech syariah regulasi","equity crowdfunding syariah","green sukuk SDGs","social sukuk impact","waqf fintech platform","zakat digital collection","BAZNAS digital ecosystem","halal industry global","modest fashion economy","halal food chain","Islamic VC microfinance","sukuk corporate issuance","SBSN surat berharga","IFSB standar global","OIC ekonomi kerjasama","ekonomi Islam kontemporer","maqashid al-shariah modern","financial inclusion Islam","digital wallet syariah","cryptocurrency halal status"]
  },
  {
    id: "msdm", name: "Manajemen SDM", faculty: "Ekonomi & Bisnis",
    keywords: ["rekrutmen seleksi","onboarding karyawan","job analysis deskripsi","kompetensi framework","talent management","high potential identification","succession planning","performance appraisal","KPI sistem","manajemen kinerja","feedback 360 derajat","career development","learning development L&D","e-learning platform","pelatihan korporat","coaching mentoring","leadership development","organizational development","change management","employee engagement","kepuasan kerja survei","employee wellbeing","burnout prevention","work-life balance","psychological safety","diversity equity inclusion","penggajian payroll","kompensasi insentif","tunjangan benefit","BPJS ketenagakerjaan","PHK regulasi UU Ketenagakerjaan","hubungan industrial","serikat pekerja","mediasi perselisihan","remunerasi sistem","grading jabatan","HR analytics","workforce planning","talent pool","remote hybrid work","employer branding","HRIS sistem informasi SDM","HR digitalisasi","agile HR","people analytics","retention strategy","exit interview","generasi Z kerja","budaya organisasi kuat","employee value proposition"]
  },
  {
    id: "bisnis-internasional", name: "Bisnis Internasional", faculty: "Ekonomi & Bisnis",
    keywords: ["ekspor impor prosedur","letter of credit","incoterms 2020","bea cukai regulasi","HS code tarif","anti-dumping countervailing","FTA perjanjian perdagangan","RCEP implementasi","CPTPP aksesi","ASEAN trade","market entry mode","joint venture asing","wholly-owned subsidiary","franchise internasional","licensing royalti","cross-cultural management","bahasa bisnis asing","negosiasi lintas budaya","due diligence internasional","country risk analisis","political risk","currency risk hedging","transfer pricing internasional","global supply chain","trade finance","export credit LPEI","ITPC pusat","trade fair pameran","market intelligence riset","competitive positioning global","brand global local","glokalisasi","multinational corporation MNC","transnational strategy","born global startup","digital export UMKM","e-commerce cross-border","marketplace global Amazon","customs broker","freight forwarder","shipping logistics","container trade","supply chain disruption","reshoring nearshoring","ESG global standards","SDGs bisnis internasional","B Corp sertifikasi","OECD guidelines MNC","geopolitical risk","bilateral investment treaty"]
  },
  {
    id: "supply-chain", name: "Manajemen Rantai Pasok", faculty: "Ekonomi & Bisnis",
    keywords: ["supply chain management","procurement strategis","vendor management","supplier evaluation","strategic sourcing","tender pengadaan","e-procurement","green procurement","category management","spend analysis","contract management","SLA KPI vendor","inventory optimization","safety stock reorder point","demand planning","S&OP sales operations planning","ERP SAP MM","warehouse management WMS","gudang otomasi AS/RS","forklift AGV robot","cross-docking fulfilment","last mile delivery","3PL 4PL logistics","freight forwarding","multimodal transport","customs clearance","incoterms kontrak","cold chain logistics","reverse logistics","circular supply chain","supply chain resilience","disruption mitigation","risk mapping supply chain","supply chain finance","invoice financing","blockchain traceability","IoT real-time tracking","AI demand forecasting","digital supply chain twin","sustainability ESG supply","Scope 3 emisi","carbon neutral logistics","APICS CPIM certification","CSCMP forum","halal logistics sertifikasi","pharma logistics GDP","kaizen supply chain","lean logistics","network optimization","spend visibility analytics"]
  },
  {
    id: "kewirausahaan", name: "Kewirausahaan & Inovasi", faculty: "Ekonomi & Bisnis",
    keywords: ["entrepreneur mindset","lean startup","customer discovery","problem-solution fit","product-market fit","pivoting strategi","MVP minimum viable product","design thinking","rapid prototyping","startup ecosystem Indonesia","venture building","corporate venture","intrapreneurship","business model innovation","platform startup","network effects","virality growth hacking","user acquisition","funnel conversion","unit economics","LTV CAC ratio","burn rate runway","fundraising Series A B C","pitch deck investor","angel investor","VC Indonesia East Ventures","Mandiri Capital MDI","startup failure learning","resilience entrepreneur","team building founding","CTO CPO CMO roles","equity split vesting","ESOP saham karyawan","valuasi startup pre-money","due diligence term sheet","cap table management","exit IPO M&A","unicorn decacorn path","UMKM digitalisasi","social entrepreneur","impact entrepreneur","sustainability B Corp","entrepreneur kampus","ekosistem startup UI ITB","incubator accelerator","venture studio","bootstrapping cashflow","customer-funded model","frugal innovation","reverse innovation"]
  },
  {
    id: "manajemen-informatika", name: "Manajemen Informatika", faculty: "Ekonomi & Bisnis",
    keywords: ["sistem informasi manajemen","analisis perancangan sistem","database management SQL","NoSQL MongoDB","data modeling ERD","UML diagram","software development lifecycle","metodologi agile scrum","kanban board","requirement analysis user story","software testing QA","UI prototyping Figma","front-end HTML CSS JavaScript","React Vue.js","back-end Node.js PHP","REST API design","cloud computing deployment AWS","Docker containerization","CI/CD pipeline GitHub Actions","keamanan aplikasi web OWASP","autentikasi OAuth JWT","GDPR PDPA compliance","ERP implementasi SAP","business analysis","process mapping BPMN","digitalisasi bisnis","transformasi digital","e-commerce platform","payment gateway midtrans Xendit","manajemen TI COBIT","ITSM ServiceNow","disaster recovery IT","SLA monitoring","analitik bisnis BI Power BI","machine learning dasar","chatbot development","mobile app development","PWA progressive web app","cybersecurity dasar","data privacy governance","IT project management","PRINCE2 PMI","low code no code","RPA UiPath","digital twin konsep","blockchain bisnis","cloud migration strategy","IT governance framework","IT audit keamanan","startup tech product management"]
  },
  {
    id: "admin-bisnis", name: "Ilmu Administrasi Bisnis", faculty: "Ekonomi & Bisnis",
    keywords: ["administrasi bisnis","teori organisasi","manajemen umum","birokrasi Weber","budaya organisasi","desain organisasi struktural","manajemen perubahan","kepemimpinan manajerial","komunikasi bisnis profesional","negosiasi kontrak","etika bisnis dan hukum","corporate governance","tanggung jawab sosial CSR","stakeholder management","manajemen operasional","proses bisnis BPM","quality management ISO 9001","balanced scorecard implementasi","KPI perusahaan","manajemen strategis","analisis industri Porter five forces","PESTEL analysis","blue ocean strategy","skenario planning","merger akuisisi due diligence","manajemen keuangan dasar","laporan keuangan analisis","business plan penulisan","feasibility study","riset pasar","segmentasi targeting positioning","marketing plan","digital transformation governance","public administration comparison","kebijakan bisnis BKPM","perizinan OSS","kemitraan BUMN swasta","PPP public private partnership","manajemen hospitality","service excellence CRM","hukum perusahaan PT CV","perlindungan konsumen","arbitrase bisnis BANI","ekspor impor administrasi","prosedur kepabeanan","SIUP TDP perizinan","hubungan industrial ketenagakerjaan","manajemen kepemimpinan lini tengah","bisnis internasional dasar","komunikasi lintas budaya"]
  },

  // === TEKNIK & SAINS === (16)
  {
    id: "informatika", name: "Informatika / Ilmu Komputer", faculty: "Teknik & Sains",
    keywords: ["algoritma dan struktur data","machine learning","deep learning","large language model","transformer architecture","computer vision","natural language processing","reinforcement learning","cloud computing AWS","Kubernetes Docker","microservices","REST API GraphQL","database SQL NoSQL","sistem operasi","jaringan komputer","keamanan siber","kriptografi","blockchain","Web3","quantum computing","edge computing","IoT platform","embedded systems","compiler design","distributed systems","parallel computing","software engineering","agile scrum","DevOps CI/CD","federated learning privacy","differential privacy","AI safety alignment","AI regulation EU Act","responsible AI","MLOps MLflow","LLMOps","model monitoring drift","vector database embedding","semantic search","RAG pipeline","fine-tuning PEFT LoRA","multimodal AI","text to image","generative video","AI agent autonomous","AR VR development","spatial computing","cybersecurity threat intelligence","zero trust architecture","post-quantum cryptography"]
  },
  {
    id: "sistem-informasi", name: "Sistem Informasi", faculty: "Teknik & Sains",
    keywords: ["enterprise architecture","ERP SAP","business intelligence","data warehouse","ETL pipeline","dashboard analytics","power BI","Tableau","data governance","master data management","IT project management","SDLC metodologi","UX/UI design","human computer interaction","e-government","sistem BPJS","digitalisasi UMKM","manajemen IT","ITSM ITIL","change management IT","information security","ISO 27001","audit sistem","disaster recovery","SLA monitoring","cloud migration","hybrid cloud","serverless architecture","low code no code","RPA automation","enterprise data management","data fabric","data mesh architecture","event-driven architecture","CQRS event sourcing","API gateway management","service mesh Istio","zero trust architecture SASE","cloud native 12-factor","GitOps DevSecOps","platform engineering","internal developer portal","observability stack OpenTelemetry","SRE reliability engineering","chaos engineering","incident management","DORA metrics","digital transformation maturity","AI governance","data ethics compliance"]
  },
  {
    id: "teknik-elektro", name: "Teknik Elektro", faculty: "Teknik & Sains",
    keywords: ["rangkaian listrik","elektronika daya","sistem tenaga listrik","transmisi distribusi","smart grid","energi terbarukan","panel surya","turbin angin","baterai lithium","EV charging","motor listrik","kontrol otomatis","PLC SCADA","embedded systems","mikrokontroler","sinyal dan sistem","komunikasi wireless","5G teknologi","antena desain","radar sistem","VLSI chip design","semiconductor","fotonik","robotika","drone UAV","IoT sensor","industri 4.0","digital twin","power electronics","inverter converter","electric vehicle Indonesia","battery storage BESS","hydrogen fuel cell","geothermal power","micro hydro turbine","floating solar PLTS","offshore wind","smart meter AMI","demand response","vehicle-to-grid V2G","wireless power transfer","electromagnetic compatibility EMC","millimeter wave 5G","satellite internet LEO","MIMO beamforming","RF circuit design","power semiconductor SiC GaN","AI power system optimization","energy storage management","grid cyber security"]
  },
  {
    id: "teknik-sipil", name: "Teknik Sipil", faculty: "Teknik & Sains",
    keywords: ["struktur beton bertulang","baja konstruksi","pondasi dalam","geoteknik","mekanika tanah","hidrologi","drainase perkotaan","irigasi pertanian","jembatan desain","jalan raya","BIM modeling","AutoCAD","SAP2000","rekayasa gempa","mitigasi bencana","konstruksi hijau","green building","sertifikasi LEED","manajemen konstruksi","K3 konstruksi","IKN Nusantara infrastruktur","tol Trans Jawa","MRT LRT Jakarta","bendungan serbaguna","PLTA mini hidro","pengelolaan limbah","sanitasi","air bersih PDAM","smart city infrastruktur","material inovatif geopolimer","precast concrete modular","structural health monitoring","seismic performance based","liquefaction mitigation","slope stability analysis","traffic engineering","transportation planning","BIM level 3 integration","4D scheduling BIM","clash detection","smart road technology","asphalt intelligent pavement","concrete durability","FRP composite struktur","carbon fiber reinforced","self-healing concrete","3D printed concrete","mass timber CLT","low carbon construction","infrastructure digital twin"]
  },
  {
    id: "teknik-mesin", name: "Teknik Mesin", faculty: "Teknik & Sains",
    keywords: ["termodinamika","mekanika fluida","perpindahan panas","kekuatan material","elemen mesin","mesin CNC","manufaktur presisi","CAD CAM","3D printing additive","material komposit","metalurgi","korosi proteksi","mesin diesel","turbin gas","HVAC sistem","pompa kompresor","maintenance reliability","vibrasi analisis","finite element method","mold injection","otomasi industri","robotic arm","hydraulic pneumatic","NDT inspection","lean manufacturing","six sigma","quality control","value stream mapping","industri baja","petrokimia proses","additive manufacturing aerospace","metal AM powder bed","surface engineering tribology","fracture mechanics fatigue","DIC digital image correlation","acoustic emission monitoring","predictive maintenance ML","digital twin machine","cyber-physical production","hybrid manufacturing","ultra-precision machining","MEMS microelectromechanical","hydrogen engine combustion","fuel cell vehicle","EV motor design","heat pump efficiency","thermoacoustics","advanced manufacturing IIoT","smart factory simulation","industri 4.0 integration"]
  },
  {
    id: "teknik-kimia", name: "Teknik Kimia", faculty: "Teknik & Sains",
    keywords: ["neraca massa energi","reaksi kimia","kinetika reaktor","operasi unit","distilasi kolom","absorpsi ekstraksi","filtrasi membran","polimer material","petrokimia downstream","refinery proses","oleokimia sawit","industri pupuk urea","biorefinery","bioproduk","fermentasi bioetanol","katalis heterogen","green chemistry","process simulation Aspen","P&ID diagram","HAZOP analisis","keselamatan kimia","limbah B3","AMDAL","clean production","carbon capture","CO2 utilization","biomassa energi","biogas methane","specialty chemicals","pharmaceutical API","biorefineri lignin","microreactor flow chemistry","intensifikasi proses","reactive distillation","dividing wall column","heat integration pinch","exergy analysis","power-to-X e-fuels","hydrogen production reforming","water electrolysis PEM","DAC direct air capture","blue hydrogen CCS","lithium battery cathode","sodium-ion battery","electrolyte design","membrane fuel cell","advanced membranes MOF","polymer electrolyte","CO2 mineralization","circular chemistry"]
  },
  {
    id: "teknik-lingkungan", name: "Teknik Lingkungan", faculty: "Teknik & Sains",
    keywords: ["pengelolaan air limbah","IPAL sistem","air bersih treatment","kualitas udara","emisi industri","pencemaran tanah","remediasi lahan","sampah B3","TPA sanitary landfill","daur ulang circular economy","AMDAL studi","UKL UPL","sertifikasi lingkungan","carbon footprint","net zero emisi","REDD+ karbon","mangrove ekosistem","coral reef restoration","biodiversitas","konservasi","renewable energy policy","solar rooftop","sampah plastik laut","extended producer responsibility","eco city planning","green infrastructure","nature based solution","climate adaptation","disaster risk reduction","SDGs 6 13 15","bioelectrochemical system","constructed wetlands","membrane bioreactor MBR","advanced oxidation processes","ozonation UV disinfection","photocatalysis TiO2","nanomaterials remediation","mine tailing treatment","acid mine drainage","phytoremediation","bioremediation in situ","PFAS kontaminasi","microplastics treatment","indoor air quality","green building certification GBCI","life cycle assessment LCA","material flow analysis MFA","industrial ecology","circular economy policy","plastic waste EPR"]
  },
  {
    id: "arsitektur", name: "Arsitektur", faculty: "Teknik & Sains",
    keywords: ["desain arsitektur","bangunan vernakular","arsitektur kontemporer","parametric design","BIM Revit","computational design","green architecture","passive cooling","biophilic design","urban design","perencanaan kota","ruang publik","heritage conservation","arsitektur tropis","material lokal","bambu konstruksi","kayu engineered","prefabrikasi modular","tiny house","co-living co-working","mixed use development","TOD transit oriented","adaptive reuse","placemaking","landscape architecture","interior desain","lighting design","acoustic design","smart building","IKN desain ibu kota","parametric Grasshopper","algorithmic design","mass customization","robotic fabrication","digital fabrication CNC","responsive facade","kinetic architecture","3D printing bangunan","modular prefab system","carbon neutral building","embodied carbon material","circular construction","low carbon concrete","timber reuse","passive house standard","net zero building","urban heat mitigation","cool roof pavement","biophilic city","walkable neighborhood"]
  },
  {
    id: "kedokteran", name: "Kedokteran Umum", faculty: "Teknik & Sains",
    keywords: ["anatomi fisiologi","patofisiologi","farmakologi","diagnosis klinis","internal medicine","bedah umum","obstetri ginekologi","pediatri","neurologi","kardiologi","onkologi","penyakit infeksi","COVID varian baru","demam berdarah","tuberculosis","stunting Indonesia","gizi klinis","kesehatan mental","psikiatri","telemedicine","AI diagnostik","robotic surgery","genomik presisi","farmakogenomik","obat biosimilar","BPJS rujukan","FKTP FKTL","akreditasi RS","dokter spesialis","pendidikan dokter","kedokteran presisi","biomarker diagnostik","liquid biopsy kanker","imunoterapi onkologi","CAR-T cell terapi","mRNA vaksin teknologi","gene therapy CRISPR","stem cell regeneratif","neuromodulation therapy","ketamine therapy research","brain-computer interface","AI diagnostik radiology","AI pathology digital","digital health wearable monitoring","remote patient monitoring RPM","hospital-at-home","value-based care","sepsis early warning AI","antimicrobial resistance stewardship","precision public health"]
  },
  {
    id: "psikologi", name: "Psikologi", faculty: "Teknik & Sains",
    keywords: ["psikologi klinis","psikologi pendidikan","psikologi industri","psikologi sosial","kesehatan mental","depresi anxiety","gangguan kepribadian","trauma PTSD","CBT terapi","mindfulness","neurosains kognitif","psikologi positif","motivasi dan emosi","kepribadian Big Five","tes psikologi","asesmen psikologis","psikometri","penelitian kualitatif","focus group","survei skala","psikologi media sosial","teknologi dan kesejahteraan","gaming disorder","bullying siber","kekerasan domestik","kesehatan kerja","burnout","resiliensi","self-compassion","psikologi lintas budaya","neuropsikologi klinis","psikologi forensik","psikofisiologi","psikologi olahraga sport","positive psychology PERMA","self-determination theory","growth mindset","psikologi organisasi I-O","psikologi konsumen","nudge behavioral economics","psikologi kesehatan","biopsychosocial model","epigenetik stres","respon stres kortisol","psikologi bencana disaster","first responder mental health","digital mental health","psikedelik terapi research","attachment theory adult","ACT acceptance commitment therapy"]
  },
  {
    id: "teknik-industri", name: "Teknik Industri", faculty: "Teknik & Sains",
    keywords: ["ergonomi desain kerja","work measurement time motion study","peta proses operasi","layout fasilitas","simulasi Arena discrete event","optimasi linier integer programming","queuing theory antrian","inventory management EOQ","reorder point safety stock","just-in-time JIT kanban","lean manufacturing","value stream mapping","kaizen continuous improvement","5S workplace organization","total productive maintenance TPM","OEE overall equipment effectiveness","six sigma DMAIC","statistical process control SPC","control chart Shewhart","Cpk process capability","FMEA failure mode analysis","root cause analysis RCA","8D problem solving","PDCA Deming cycle","ISO 9001 QMS","supply chain management SCM","logistics distribution","warehouse management WMS","demand forecasting ML","S&OP planning","ERP SAP production planning","project management PERT CPM","agile project","digital manufacturing","cyber-physical systems industri 4.0","IIoT industrial internet of things","digital twin manufacturing","AI quality inspection","collaborative robot cobot","additive manufacturing industri","green manufacturing","sustainability LCA","ekonomi sirkular industri","assembly line balancing","simulation Tecnomatix","human factors safety","product lifecycle management PLM","smart factory automation","data analytics production","biaya produksi analisis","studi kelayakan industri"]
  },
  {
    id: "matematika", name: "Matematika", faculty: "Teknik & Sains",
    keywords: ["kalkulus diferensial integral","aljabar linear matriks","geometri analitik","topologi ruang metrik","analisis real","analisis kompleks","persamaan diferensial ODE PDE","matematika diskret","teori grafik","kombinatorik","teori peluang","statistika matematika","probabilitas stokastik","rantai Markov","proses stokastik","metode numerik","komputasi ilmiah Python NumPy","MATLAB Octave","R statistika","analisis data eksploratori","machine learning dasar","data science matematika","optimasi konveks","riset operasi","pemrograman linier","teori permainan Nash","teori informasi Shannon","kriptografi matematika RSA","analisis fungsional","ruang Hilbert","aljabar abstrak grup ring","teori bilangan","matematika finansial","aktuaria dasar","model matematika epidemi SIR","pemodelan populasi Lotka-Volterra","transformasi Laplace Fourier","teori kontrol matematis","logika proposisi predikat","teori himpumat","geometri diferensial","geometri aljabar","matematika fisika","matematika terapan","olimpiade matematika IMO","topology algebraic","measure theory Lebesgue","partial differential equations numerik","mathematical modeling social","graph neural network","topological data analysis TDA"]
  },
  {
    id: "fisika", name: "Fisika", faculty: "Teknik & Sains",
    keywords: ["mekanika klasik Newton Lagrange","termodinamika statistika","elektrodinamika Maxwell","mekanika kuantum Schrodinger","relativitas khusus Einstein","relativitas umum gravitasi","fisika partikel standar model","fisika nuklir","astrofisika kosmologi","fisika plasma","kondensasi materi terkondensasi","superkonduktivitas","magnetisme material","semikonduktor fisika","laser optika","fotonik","nanofisika nanomaterial","fisika komputasi","simulasi molekuler Monte Carlo","metode elemen berhingga FEM","komputasi kuantum","qubit quantum gate","quantum entanglement","kriptografi kuantum","sensor kuantum","fisika medis radioterapi","pencitraan MRI fMRI","fisika material baru","material 2D graphene","topological insulator","fisika lingkungan energi","sel surya efisiensi perovskite","nuklir fisi fusi","reaktor PLTN SMR","detektor partikel","gelombang gravitasi LIGO","teleskop JWST observasi","fisika atmosfer iklim","geofisika eksplorasi","seismologi gempa","fisika eksperimen","pengukuran presisi standar","akselerator partikel CERN LHC","dark matter dark energy","neutrino physics","string theory","quantum field theory","condensed matter topological","biophysics membrane","statistical mechanics"]
  },
  {
    id: "geologi", name: "Geologi", faculty: "Teknik & Sains",
    keywords: ["geologi struktur lipatan sesar","petrologi batuan beku","mineralogi kristalografi","geomorfologi bentang alam","stratigrafi umur relatif","sedimentologi fasies","paleontologi fosil","geokimia unsur jejak","geofisika eksplorasi seismik","seismologi gempa Indonesia","vulkanologi gunung api Indonesia","ring of fire","geohazard bencana geologi","tanah longsor mitigasi","likuifaksi","geologi lingkungan","hidrogeologi air tanah","geothermal panas bumi","PLTP eksplorasi geothermal","minyak gas bumi petroleum","basin analysis","eksplorasi migas","pemetaan geologi lapangan","GPS geodesi GNSS","remote sensing geologi","GIS geologi spasial","citra satelit analisis","batubara sumber daya","nikel laterit Indonesia","emas porfiri deposit","mineral kritis lithium kobalt","tembaga geologi porfiri","timah Indonesia bangka","geologi kelautan sedimen","geologi kuarter paleoklimat","geologi teknik pondasi","geologi forensik","geopark UNESCO Indonesia","warisan geologi","carbon capture storage CCS","sumber daya mineral nasional","kebijakan pertambangan ESDM","geologi IKN Nusantara","landslide susceptibility mapping","volcanology monitoring","earthquake early warning","USGS database","geoscience data analysis","mineral prospectivity mapping","geospatial AI"]
  },
  {
    id: "teknik-biomedis", name: "Teknik Biomedis", faculty: "Teknik & Sains",
    keywords: ["peralatan medis medical device","alat diagnostik in vitro","imaging MRI CT scan","X-ray radiologi","ultrasound USG","ECG EKG jantung","EEG otak","biosensor wearable","point of care testing","lab on a chip microfluidics","prothesis implan","biomaterial biokompatibilitas","titanium kobalt implan","polimer biodegradable","rekayasa jaringan tissue engineering","sel punca stem cell aplikasi","bioprinting 3D jaringan","organ organoid","neural interface BCI","deep brain stimulation","cochlear implant","retinal prosthesis","robotic surgery da Vinci","laparoskopi minimal invasif","telemedicine device","remote patient monitoring","digital health wearable","smartwatch kesehatan biometrik","AI diagnostik radiologi","computer-aided detection CAD","DICOM standar","HL7 FHIR interoperabilitas","regulasi BPOM alkes","FDA clearance 510k","ISO 13485 quality","clinical trial alkes","uji sterilisasi metode","cleanroom GMP farmasi","signal processing biomedis","pemrosesan citra medis","kompresi data medis","database EHR","keamanan data kesehatan","nanomedicine drug delivery","theranostics","exoskeleton rehab robot","soft robotics medis","haptic feedback surgery","augmented reality surgery","hospital IoT infrastructure"]
  },
  {
    id: "data-science", name: "Ilmu Data & Data Science", faculty: "Teknik & Sains",
    keywords: ["statistika terapan inferensi","probabilitas distribusi","machine learning supervised unsupervised","deep learning arsitektur CNN RNN","transformer BERT GPT","large language model LLM","fine-tuning LoRA PEFT","RAG retrieval augmented generation","computer vision object detection","NLP sentiment analysis","named entity recognition","time series forecasting ARIMA LSTM","gradient boosting XGBoost LightGBM","random forest ensemble","feature engineering selection","dimensionality reduction PCA t-SNE","clustering k-means DBSCAN","anomaly detection","recommender system collaborative filtering","A/B testing experimentation","causal inference propensity score","data engineering pipeline","ETL Apache Spark","data warehouse Snowflake BigQuery","dbt data build tool","Apache Airflow orchestration","cloud platform AWS GCP Azure","SQL advanced analytics window","NoSQL MongoDB Cassandra","graph database Neo4j","data visualization Tableau D3.js","dashboarding BI tools","MLOps model deployment","FastAPI model serving","Docker Kubernetes ML","data quality monitoring","model explainability SHAP LIME","fairness AI bias detection","privacy federated learning","synthetic data generation","data storytelling narrative","Python pandas scikit-learn","Julia R computing","productionize ML model","stream processing Kafka","data lakehouse Delta Lake","geospatial data analysis","NLP Bahasa Indonesia","chatbot development Rasa","sports analytics","healthcare analytics"]
  },

  // === SOSIAL & HUMANIORA === (12)
  {
    id: "ilmu-komunikasi", name: "Ilmu Komunikasi", faculty: "Sosial & Humaniora",
    keywords: ["teori komunikasi","komunikasi massa","jurnalisme digital","media sosial","influencer economy","konten kreator","viral content","algoritma platform","filter bubble","echo chamber","disinformasi hoaks","fact-checking","media literacy","public relations","corporate communication","crisis communication","brand journalism","video podcasting","new media","streaming platform","TikTok journalism","citizen journalism","data journalism","investigasi OSINT","media ownership","ekonomi media","iklan digital","audience analytics","komunikasi politik","kampanye media sosial","komunikasi kesehatan","health communication","komunikasi lingkungan","climate communication","science communication","komunikasi bencana BNPB","media dan demokrasi","surveillance capitalism Zuboff","attention economy","platform governance","content moderation","deplatforming","hate speech regulation","dark patterns UX","media bias detection","automated fact-checking","AI generated content ethics","komunikasi pemberdayaan","strategic communication","narrative framing theory"]
  },
  {
    id: "hubungan-internasional", name: "Hubungan Internasional", faculty: "Sosial & Humaniora",
    keywords: ["teori HI realisme","liberalisme konstruktivisme","diplomasi bilateral","multilateral ASEAN","PBB mekanisme","geopolitik Indo-Pasifik","Laut China Selatan","AUKUS quad","Belt Road Initiative","de-dollarisasi BRICS","perdagangan WTO","sanksi ekonomi","soft power budaya","public diplomacy","diplomasi digital","cyber sovereignty","climate diplomacy","COP29 negosiasi","peacebuilding","konflik Rusia-Ukraina","Timur Tengah Israel","Myanmar krisis","hak asasi manusia","refugee pengungsi","humanitarian aid","international development","ODA bantuan","NGO internasional","rezim internasional","global governance","regional integration theory","ASEAN way","Indo-Pacific concept","Quad minilateral","US-China decoupling","tech war semiconductor","supply chain security","food security geopolitics","water security","energy geopolitics","green transition geopolitics","critical minerals race","space race militarization","cyberwarfare state actors","information warfare","disinformation campaigns","election interference","lawfare diplomacy","global governance reform","UN Security Council reform"]
  },
  {
    id: "sosiologi", name: "Sosiologi", faculty: "Sosial & Humaniora",
    keywords: ["struktur sosial","stratifikasi kelas","mobilitas sosial","modal sosial Bourdieu","teori Giddens","sosiologi digital","platform dan masyarakat","komunitas online","gerakan sosial","aktivisme digital","feminisme interseksional","ras dan etnisitas","multikulturalisme","identitas budaya","agama dan modernitas","sosiologi agama","sekularisasi","radikalisme","deradikalisasi","ketimpangan global","kemiskinan urban","slum kampung","gentrifikasi","migrasi urbanisasi","sosiologi pangan","ketahanan pangan","perubahan iklim sosial","pandemi dan masyarakat","demografi aging","generasi Z Alpha","sosiologi vaksinasi","sosiologi tubuh body","disability studies","sosiologi kesehatan","sosiologi ekonomi","sociology of knowledge","sociology of science","Bourdieu arena field","Foucault biopolitik","surveillance society","neoliberalisme dan subjek","precariat Guy Standing","platform labor gig","sosiologi generasi","digital native socialization","post-pandemic society","sosiologi pendidikan","sosiologi olahraga","sosiologi teknologi AI","environmental sociology"]
  },
  {
    id: "ilmu-politik", name: "Ilmu Politik", faculty: "Sosial & Humaniora",
    keywords: ["sistem politik demokrasi","otoritarianisme","pemilu Indonesia","Pilkada serentak","partai politik","koalisi pemerintahan","DPR legislasi","eksekutif Presiden","yudikatif MK","otonomi daerah","desentralisasi fiskal","korupsi politik","KPK pemberantasan","politik identitas","populisme","oligarki politik","political economy","civil society","LSM advokasi","media dan demokrasi","survei opini publik","Indikator LSI SMRC","opini legislatif","pemerintahan digital","e-democracy","smart governance","birokrasi reformasi","kebijakan publik","policy analysis","komparasi politik","regime type classification","hybrid regime","electoral authoritarianism","democratic backsliding","populisme global","illiberalisme","disinformasi dan pemilu","micro-targeting politik","Cambridge Analytica","data dan kekuasaan","political behavior","psikologi politik","partisan identity","polarisasi afektif","deliberative democracy","participatory budgeting","civic tech","e-voting","political economy rents","state-business relations"]
  },
  {
    id: "antropologi", name: "Antropologi", faculty: "Sosial & Humaniora",
    keywords: ["etnografi fieldwork","kebudayaan lokal","adat istiadat","hukum adat","masyarakat adat","MIFEE Papua","suku terasing","warisan budaya tak benda","UNESCO intangible","ritual dan simbol","gender dan budaya","tubuh dan kuasa","foodways kuliner","pariwisata budaya","museum etnografi","arkeologi budaya","folkore","tradisi lisan","oral history","visual anthropology","digital ethnography","digital culture","algorithmic bias","techno-anthropology","anthropocene","ecological anthropology","pangan lokal","obat tradisional","biodiversitas pengetahuan lokal","dekolonisasi ilmu","indigenous knowledge systems","traditional ecological knowledge","biokultural","kognitif linguistik","multispecies anthropology","more than human","anthropology of AI","algorithmic anthropology","digital divide","digital inclusion","cyberculture","gaming culture","fan community","K-pop fandom Indonesia","cosplay subculture","makerspaces tinkering","repair culture","anthropology of finance","economic anthropology","gift economy Mauss","medical anthropology"]
  },
  {
    id: "pendidikan-matematika", name: "Pendidikan Matematika", faculty: "Sosial & Humaniora",
    keywords: ["kurikulum matematika Merdeka","diferensial kalkulus","aljabar linear","statistika inferensial","probabilitas","topologi","analisis real","geometri Euklid","teori bilangan","kombinatorik","pembuktian formal","PISA matematika","numerasi literasi","pendidikan inklusif","learning disability dyscalculia","game-based learning matematika","STEM integratif","flipped classroom","problem-based learning","teknologi GeoGebra","Desmos","Python statistika","computational thinking","coding di sekolah","assessment formatif","portofolio siswa","pedagogik matematika","lesson study","guru matematika","olimpiade sains nasional","lesson study Jepang collaborative","realistic mathematics education","critical mathematics education","ethnomathematics","mathematical modeling terapan","PISA 2025 framework","TIMSS assessment","AI mathematics tutor","ChatGPT in math","calculus reform","statistics first approach","data science pendidikan","R Python di kelas","visualization interaktif","dynamic geometry 3D","GeoGebra AR","mathematics anxiety treatment","number sense development","misconception diagnosis","STEM project based"]
  },
  {
    id: "sastra-indonesia", name: "Sastra Indonesia", faculty: "Sosial & Humaniora",
    keywords: ["sastra kontemporer","novel Indonesia modern","puisi esai","cerpen digital","sastra siber","Wattpad Indonesia","fan fiction","penerbitan indie","self-publishing","Gramedia ekosistem","penulis perempuan","sastra diaspora","kajian postkolonial","Pramoedya Ananta Toer","Ayu Utami","Andrea Hirata","film adaptasi sastra","budaya literasi","membaca digital","e-book audiobook","kamus Besar Bahasa Indonesia","bahasa gaul","slang media sosial","bahasa daerah","revitalisasi bahasa","terjemahan sastra","kritik sastra","esai sastra","jurnalisme sastra","linguistik forensik","sastra digital e-literature","generative fiction AI","prompt writing kreatif","NLP bahasa Indonesia","corpus linguistik","big data sastra","distant reading Franco Moretti","world literature","comparative literature","transnational literature","sastra lingkungan ecocriticism","posthumanist literature","disability narratives","queer literary studies","sastra populer webtoon","self-publishing royalti digital","machine translation sastra","audio drama podcast","sastra resistensi","dekolonisasi kanon sastra"]
  },
  {
    id: "hukum", name: "Ilmu Hukum", faculty: "Sosial & Humaniora",
    keywords: ["hukum perdata","hukum pidana","hukum tata negara","hukum administrasi","hukum internasional","hukum bisnis","hukum ketenagakerjaan","hukum pertanahan","hukum adat","hukum lingkungan","KUHP baru","UU Cipta Kerja","UU ITE","hukum siber","data privacy","PDPA GDPR","kekayaan intelektual","paten merek hak cipta","hukum startup","kontrak elektronik","arbitrase BANI","mediasi ADR","litigasi perdata","pidana korupsi","pencucian uang TPPU","fintech legal","hukum AI","regulasi kripto","MK constitutional review","judicial review","hukum teknologi","hukum kecerdasan buatan","regulasi AI Indonesia","regulasi cryptocurrency","hukum media sosial","hukum perlindungan data","creative commons","open source lisensi","hukum ruang angkasa","space law","hukum laut internasional UNCLOS","sengketa Laut China Selatan","hukum iklim Paris Agreement","carbon trading law","greenwashing liability","ESG disclosure regulasi","hukum perusahaan transnasional","class action","public interest litigation","restorative justice hukum"]
  },
  {
    id: "ilmu-perpustakaan", name: "Ilmu Perpustakaan & Informasi", faculty: "Sosial & Humaniora",
    keywords: ["manajemen koleksi","katalogisasi metadata","sistem informasi perpustakaan","OPAC digital","repositori institusional","open access publishing","scholarly communication","bibliometrika","scientometrics","h-index","Scopus Web of Science","knowledge management","arsip digital","preservasi digital","cloud storage arsip","data curation","linked data","ontologi informasi","information retrieval","user experience perpustakaan","information literacy","perpustakaan sekolah","perpustakaan publik","perpustakaan digital","e-library","Mendeley Zotero","plagiarisme deteksi","library 2.0","social library","literasi digital","open science movement","preprint server","research data management DMP","FAIR data principles","scholarly metrics altmetrics","ResearchGate Academia.edu","predatory journal detection","impact factor JIF CiteScore","research evaluation","library analytics","learning analytics library","library space design","maker space perpustakaan","library instruction","information literacy ACRL","transliteracy","digital citizenship","AI library services","chatbot perpustakaan","data science library","bibliotherapy"]
  },
  {
    id: "pgsd", name: "PGSD (Pendidikan Dasar)", faculty: "Sosial & Humaniora",
    keywords: ["kurikulum Merdeka Belajar","Pancasila pendidikan karakter","literasi numerasi dasar","pembelajaran berdiferensiasi","asesmen formatif sumatif","profil pelajar Pancasila","projek penguatan profil","portofolio siswa","Google Classroom","teknologi pembelajaran","Canva pendidikan","YouTube edukasi","TikTok guru","pendidikan inklusi","ABK kebutuhan khusus","psikologi perkembangan anak","teori Piaget Vygotsky","scaffolding","zona perkembangan proksimal","cooperative learning","project-based learning","inquiry learning","PJOK","seni budaya SD","guru penggerak","PMM Platform Merdeka Mengajar","akreditasi sekolah","rapor pendidikan","PPDB zonasi","pendidikan karakter","pendidikan karakter holistik","proyek lintas mapel","STEM SD terapan","computational thinking SD","coding visual Scratch","assessment-as-learning","umpan balik konstruktif","portofolio digital siswa","orang tua dan sekolah","kemitraan masyarakat","ekosistem sekolah","pendidikan multikultural SD","toleransi kebhinekaan","anti-bullying program","sekolah ramah anak SRA","lesson study SD","literasi sains SD","matematika SD hands-on","student agency","restorative discipline","diferensiasi produk proses konten"]
  },
  {
    id: "filsafat", name: "Filsafat", faculty: "Sosial & Humaniora",
    keywords: ["epistemologi pengetahuan","ontologi keberadaan","metafisika","etika teori","utilitarianisme Bentham Mill","deontologi Kant","virtue ethics Aristotle","kontraktarianisme Rawls","filsafat politik","filsafat hukum","filsafat bahasa Wittgenstein","filsafat ilmu","filsafat sains","paradigma Kuhn","program riset Lakatos","filsafat mind","consciousness problem","qualia subjektivitas","filsafat teknologi","AI dan etika","transhumanisme","posthumanisme","bioetika","etika lingkungan","deep ecology","cosmopolitanisme global","filsafat agama","teodisi","pluralisme religius","Pancasila sebagai filsafat","positivisme hukum","hermeneutika Gadamer","fenomenologi Husserl Heidegger","eksistensialisme Sartre","filsafat analitik","pragmatisme Dewey","strukturalisme poststrukturalisme","dekonstruksi Derrida","kritisisme Habermas","feminisme filsafat","teori kritis Frankfurt","filsafat ekonomi","rasionalitas terbatas","teori pilihan sosial","logika modal","logika fuzzy","penalaran abduktif","argumentation theory","filsafat pendidikan","retorika kuno modern","applied ethics case study"]
  },
  {
    id: "sejarah", name: "Sejarah", faculty: "Sosial & Humaniora",
    keywords: ["historiografi metodologi","sumber primer sejarah","arsip kolonial ANRI","sejarah lisan oral history","sejarah Indonesia kuno","kerajaan Majapahit Sriwijaya","sejarah Islam Nusantara","VOC kolonialisme","pergerakan nasional","Sumpah Pemuda 1928","proklamasi kemerdekaan 1945","Orde Lama Soekarno","PKI 1965","Orde Baru Soeharto","reformasi 1998","sejarah kontemporer","sejarah ekonomi","sejarah sosial","sejarah perempuan gender","sejarah lingkungan","historical GIS","digital humanities","arsip digital","memory studies","trauma kolektif","reconciliation sejarah","dekolonisasi narasi","sejarah global","dunia Islam Usmani","kolonialisme dan dekolonisasi","perang dunia geopolitik","Cold War Indonesia","sejarah Tiongkok India ASEAN","migrasi diaspora Tionghoa","peranakan budaya","sejarah agraria tanah","cultuurstelsel","sejarah kota Jakarta Batavia","sejarah Bali kesenian","sejarah Jawa pesisir","sejarah Borneo Kalimantan","sejarah Papua modernitas","numismatik arkeologi","museum kuratorial","public history","sejarah dan film media","revisionism historikal","post-colonial theory","subaltern studies","Orientalisme Said","sejarah lisan Indonesia"]
  },

  // === KESEHATAN & BIOLOGI === (8)
  {
    id: "kesmas", name: "Kesehatan Masyarakat", faculty: "Kesehatan & Biologi",
    keywords: ["epidemiologi","biostatistik","kesehatan lingkungan","K3 keselamatan kerja","promosi kesehatan","kebijakan kesehatan","BPJS JKN","UHC universal health","stunting intervensi","gizi masyarakat","penyakit tidak menular","diabetes hipertensi","mental health policy","kesehatan reproduksi","KB keluarga berencana","vaksinasi imunisasi","surveilans penyakit","KLB outbreak","one health","zoonosis","resistensi antibiotik","air bersih sanitasi","WASH","perubahan iklim kesehatan","panas ekstrem","polusi udara","aedes dengue","malaria eliminasi","TB strategi","COVID lesson learned","health system strengthening","Puskesmas transformasi","FKTP gates BPJS","JKN evaluasi","ekuitas kesehatan","sosial determinan kesehatan","social gradient health","health in all policies","intersectoral collaboration","total coverage evaluation","community health worker","kader posyandu digital","community diagnosis PHA","planetary health","antimicrobial resistance AMR","microbiome populasi","epigenomik populasi","health technology assessment","big data epidemiology","geospatial health mapping"]
  },
  {
    id: "farmasi", name: "Farmasi", faculty: "Kesehatan & Biologi",
    keywords: ["kimia farmasi","farmakognosi","farmakologi klinis","biofarmasi","farmakokinetik","formulasi sediaan","tablet kaplet","injeksi steril","sediaan topikal","CDOB distribusi","CPOB manufaktur","uji stabilitas","disolusi uji","QC quality control","validasi metode","BPOM regulasi","OWA obat keras","obat generik","biosimilar biologi","terapi target kanker","obat penyakit langka","herbal fitofarmaka","jamu tradisional","kosmetik halal","supplement nutraceutical","drug interaction","medication error","clinical pharmacy","pharmacovigilance","obat digital e-prescription","pharmaceutical 4.0","artificial intelligence drug discovery","in silico drug design","structure-based drug design","QSAR modeling","molecular docking","ADMET prediction","clinical trial phase","adaptive trial design","patient reported outcome","pharmacoeconomics","cost-effectiveness analysis ICER","HTA health technology assessment","real world evidence","patient registry","pharmacogenomics panel","precision dosing","therapeutic drug monitoring","biosimilar development approval","drug repurposing","RNA therapeutics siRNA"]
  },
  {
    id: "biologi", name: "Biologi", faculty: "Kesehatan & Biologi",
    keywords: ["biologi sel","genetika molekuler","evolusi Darwinian","ekologi populasi","botani sistematik","zoologi vertebrata","biologi kelautan","biologi tanah","taksonomi DNA barcode","biologi konservasi","spesies endemik Indonesia","Wallacea biogeografi","IUCN red list","CITES perlindungan","coral triangle","hutan hujan tropis","mangrove ekosistem","keanekaragaman hayati","bioprospekting","mikrobioma usus","gut-brain axis","epigenetik","CRISPR gene editing","bioinformatika","genomik metagenomik","proteomik","biologi sintetik","eDNA monitoring","rewilding restoration","one health ecology","metagenomik lingkungan","citizen science biology","gamification biodiversity","Flora Fauna Indonesia database","GBIF species data","iNaturalist platform","biologi konservasi kuantitatif","population viability analysis","habitat connectivity landscape","landscape genetics","disease ecology","zoonotic spillover","host-pathogen interface","virome microbiome","holobiont concept","endosymbiosis theory","horizontal gene transfer","adaptive radiation","coevolution arms race","bioinformatics pipeline","systems biology"]
  },
  {
    id: "bioteknologi", name: "Bioteknologi", faculty: "Kesehatan & Biologi",
    keywords: ["rekayasa genetika","CRISPR Cas9","transgenik tanaman","kultur jaringan","bioreaktor","fermentasi industri","enzim industrial","bioplastik","biofuel generasi 2","bioetanol singkong","biogas biomassa","vaksin rekombinan","terapi gen","CAR-T cell","antibodi monoklonal","diagnostik PCR","sequencing NGS","metagenomik","bioinformatika pipeline","protein engineering","directed evolution","synthetic biology","cell-free system","bioprinting","organ-on-chip","precision fermentation","alternative protein","cultivated meat","mycoprotein","algae bioproduct","protein modeling AlphaFold","structure prediction AI","metabolic engineering","flux balance analysis","genome-scale model","optogenetics","organoid cerebral","xenotransplantation pig-to-human","brain organoid ethics","synthetic genome","minimal genome","xenobiology","unnatural amino acids","click chemistry bioconjugate","aptamer selection SELEX","nanobody antibody fragment","mRNA therapeutics","lipid nanoparticle delivery","phage therapy","microbiome engineering"]
  },
  {
    id: "keperawatan", name: "Keperawatan", faculty: "Kesehatan & Biologi",
    keywords: ["asuhan keperawatan","diagnosa keperawatan NANDA","intervensi NIC","outcome NOC","keperawatan medikal bedah","keperawatan anak","keperawatan maternitas","keperawatan jiwa","keperawatan komunitas","keperawatan kritis ICU","patient safety","sasaran keselamatan pasien","komunikasi SBAR","handover perawat","infeksi nosokomial","pencegahan HAI","manajemen nyeri","wound care","evidence-based nursing","clinical pathway","telenursing","home care","perawat lansia","gerontologi","palliative care","nurse practitioner","keperawatan bencana","tanggap darurat","PPNI organisasi","uji kompetensi UKOM","perawat spesialis kritis","perawat spesialis onkologi","perawat spesialis jiwa","NERS profesi","nursing informatics","EHR nursing documentation","clinical decision support","sepsis protocol early detection","code blue team","ventilator management ICU","patient delirium prevention","fall prevention program","pressure injury prevention","medication reconciliation","discharge planning","transitional care","nurse-led clinic","advanced practice nursing","telenursing remote monitoring","nursing leadership management"]
  },
  {
    id: "kedokteran-gigi", name: "Kedokteran Gigi", faculty: "Kesehatan & Biologi",
    keywords: ["anatomi gigi mulut","histologi jaringan gigi","ilmu material kedokteran gigi","konservasi gigi karies","komposit resin GIC","endodontik saluran akar","periodontik penyakit gusi","ortodontik maloklusi","aligner Invisalign clear","prostodontik mahkota gigi tiruan","implan gigi osseointegration","denture gigi palsu","bedah mulut ekstraksi","impaksi wisdom tooth","implant surgery immediate","rahang TMJ disorder","oral medicine diagnosis","kanker mulut deteksi dini","stomatitis ulser","radiologi dental CBCT","panoramik radiografi","dental material inovasi","CAD/CAM cerec chair-side","digital dentistry workflow","3D printing dental","AI diagnostik karies caries","teledentistry","kesehatan gigi masyarakat","fluoride program","pit fissure sealant","sekolah kesehatan gigi","BPJS gigi akses","regulasi dokter gigi","PDGI organisasi","spesialisasi kedokteran gigi","biomimerik gigi","regenerasi jaringan periodontal","stem cell dental pulp","peri-implantitis treatment","gigi susu permanen tumbuh","bruxism penanganan splint","bleaching whitening profesional","veneer estetik porcelain","composite bonding","smile design digital","photobiomodulation laser","saliva diagnostics","oral microbiome","minimally invasive dentistry"]
  },
  {
    id: "kebidanan", name: "Kebidanan", faculty: "Kesehatan & Biologi",
    keywords: ["asuhan kebidanan","kehamilan trimester ANC","pemeriksaan Leopold","DJJ denyut jantung janin","persalinan normal fisiologis","partograf persalinan","IMD inisiasi menyusu dini","ASI eksklusif","perawatan neonatus","bayi prematur NICU","berat lahir rendah BBLR","komplikasi kehamilan","preeklamsi eklamsi","plasenta previa","solusio plasenta","perdarahan postpartum HPP","keluarga berencana KB","kontrasepsi pilihan","AKDR IUD","implan KB","MOP MOW sterilisasi","kesehatan reproduksi perempuan","kanker serviks skrining","IVA tes","Pap smear","HPV vaksin","endometriosis","PCOS sindrom","menopause manajemen","kekerasan gender reproduksi","kebidanan forensik","BPJS persalinan","puskesmas kebidanan","bidan desa terpencil","AKI angka kematian ibu","AKB angka kematian bayi","SDGs kesehatan ibu","kebidanan komunitas","midwifery evidence-based","skill lab simulasi persalinan","OSCE kompetensi bidan","Uji Kompetensi Bidan","IBI organisasi bidan","kebidanan digital telehealth","fisiologi laktasi","gizi ibu hamil","postpartum depression","water birth alternative","birth ball technique","hypnobirthing","doula support"]
  },
  {
    id: "fisioterapi", name: "Fisioterapi", faculty: "Kesehatan & Biologi",
    keywords: ["anatomi muskuloskeletal","kinesiologi gerak tubuh","biomekanik sendi otot","neurologi klinis fisioterapi","pemeriksaan fisioterapi asesmen","tes khusus ortopedi","diagnosis fisioterapi ICF","fisioterapi ortopedi","fisioterapi neurologi","stroke rehabilitasi","cerebral palsy anak","spinal cord injury rehab","fisioterapi pediatri","fisioterapi geriatri","fisioterapi kardiopulmonal","fisioterapi olahraga cedera","cedera ACL lutut rehab","bahu rotator cuff","tendinopati achilles","LBP nyeri punggung bawah","manual therapy","joint mobilization Maitland","soft tissue mobilization","traksi tulang belakang","elektroterapi TENS","ultrasound terapi terapeutik","laser terapi LLLT","dry needling","kinesio taping","latihan terapeutik exercise","strength training rehabilitasi","proprioception training","balance vestibular rehab","hydrotherapy","aquatic therapy","ergonomi kerja fisioterapi","alat bantu orthosis prothesis","wheelchair assessment fitting","outcome measures PSFS","functional independence measure","home exercise program","telerehabilitation digital","fisioterapi berbasis bukti EBP","reflective practice","IFI WCPT standar","IKAFU regulasi Indonesia","fitness preventif kebugaran","pain neuroscience education","graded exposure therapy","sports return-to-play protocol"]
  },

  // === SENI, DESAIN & MEDIA === (8)
  {
    id: "dkv", name: "Desain Komunikasi Visual", faculty: "Seni, Desain & Media",
    keywords: ["tipografi","layout desain","identitas brand","logo design","visual hierarchy","color theory","ilustrasi digital","motion graphics","UI UX design","Figma prototyping","Adobe Creative Suite","After Effects","video editing","animasi 2D 3D","3D modeling Blender","AR VR experience","packaging design","editorial design","infografis","data visualization","desain poster","campaign visual","social media visual","AI generative art","Midjourney Stable Diffusion","NFT digital art","brand guideline","design system","accessibility desain","sustainable design","speculative design futures","critical design activism","social design inclusif","environmental graphic","wayfinding signage","exhibition design","retail design POS","motion identity branding","kinetic typography","interactive installation","immersive experience","projection mapping","creative coding p5.js","generative design","parametric typography","variable font","type design Indonesia","design thinking methodology","user research UX","design sprint","service design blueprint"]
  },
  {
    id: "film-tv", name: "Film & Televisi", faculty: "Seni, Desain & Media",
    keywords: ["sinematografi","sutradara directing","penulisan skenario","produksi film","post-production","color grading","sound design","scoring musik","dokumenter","film pendek","film panjang","festival film","streaming platform Netflix","Disney+","layanan lokal Vidio WeTV","hikmah film religi","film horor Indonesia","film action","animasi Indonesia","web series","konten kreator YouTube","short-form TikTok","podcast video","live streaming","OTT regulasi","sensor KPI","rating Nielsen","distribution deal","film fund BUMN","transmedia storytelling","IP intellectual property","cinematic universe","content strategy platform","audience development","crowdfunding film Indonesia","impact documentary","social impact campaign","film restoration digital","AI in film production","virtual production LED stage","real-time VFX","generative visual effects","AI dubbing localization","film score composing","Dolby Atmos sound","immersive cinema","AR interactive film","interactive narrative","screenplay coverage analysis","film commissioning pitching"]
  },
  {
    id: "musik", name: "Musik", faculty: "Seni, Desain & Media",
    keywords: ["teori musik","harmoni","komposisi","aransemen","orkestra","musik tradisional gamelan","keroncong","dangdut","pop Indonesia","indie folk","hip hop rap Indonesia","EDM elektronik","produksi DAW","Ableton Logic Pro","mixing mastering","vokal teknik","live performance","sound engineering","studio recording","distribusi digital Spotify","Apple Music","DistroKid","monetisasi streaming","sync licensing","NFT musik","AI komposisi","vocaloid","virtual concert","manajemen artis","label rekaman","ethnomusicology","musik dan identitas budaya","musik diaspora","music therapy neurologic","musik Islam nasyid qasidah","gamelan kontemporer","world music fusion","afrobeats global","K-pop production idol system","music business indie","music publishing rights","performing rights YKCI","sync placement supervisor","playlist curator algorithmic","algorithmic playlist Spotify","music streaming economy","AI music generation Suno","scoring film media","podcast audio drama","music education pedagogy"]
  },
  {
    id: "pariwisata", name: "Pariwisata", faculty: "Seni, Desain & Media",
    keywords: ["destinasi wisata Indonesia","Bali branding","super priority destination","Danau Toba","Labuan Bajo","Mandalika","Likupang","Borobudur","wisata halal","wisata alam ecotourism","agrowisata","wisata budaya","MICE convention","meeting incentive","hotel management","revenue management","OTA online travel","Traveloka booking.com","hospitality service","guest experience","sustainable tourism","overtourism","carrying capacity","community based tourism","digital nomad","bleisure travel","post-pandemic recovery","pariwisata 5.0","AI personalized travel","travel influencer","sustainable destination management","DMO destination marketing organization","place branding","destination competitiveness","smart tourism","tourism data analytics","big data tourism","visitor management system","dynamic pricing hotel","revenue management advanced","ancillary revenue upselling","loyalty program","metaverse tourism","virtual tour","AR heritage tourism","gamification travel","wellness tourism spa","medical tourism","culinary tourism gastronomy","regenerative tourism","slow travel movement"]
  },
  {
    id: "olahraga", name: "Ilmu Keolahragaan", faculty: "Seni, Desain & Media",
    keywords: ["fisiologi olahraga","biomekanik","nutrisi atlet","pelatihan periodisasi","strength conditioning","sport medicine","cedera penanganan","rehabilitasi fisik","sport psychology","mental toughness","analitik performa","GPS tracking atlet","wearable sensor","video analysis","eSports","sport business","manajemen event","olimpiade","Asian Games","SEA Games Indonesia","Timnas Garuda","Badminton Indonesia PBSI","PSSI reformasi","Sport Science","coaching metodologi","talent identification","sport for development","doping WADA","anti-doping regulasi","sport analytics AI","machine learning performance","biomechanics AI","AI scouting talent","wearable biometric athlete","sleep recovery HRV","altitude training","heat acclimatization","sport nutrition ketogenic","hydration sweat rate","technology in sport ethics","para sport Paralympic","adaptive sport","sport psychology CBT","imagery visualization","mindfulness athlete","leadership team sport","sports law CAS","sport broadcasting media","athlete branding sponsorship","sport venture capital investment"]
  },
  {
    id: "desain-produk", name: "Desain Produk Industri", faculty: "Seni, Desain & Media",
    keywords: ["desain produk konsep","ideasi sketching rapid","prototyping rapid","CAD SolidWorks Fusion 360","rendering KeyShot Blender","ergonomi produk","human factors desain","universal design","inclusive design accessibility","material selection guide","polimer plastik desain","logam casting forging","keramik komposit","manufaktur proses","injection molding","CNC machining","3D printing FDM SLA SLS","desain untuk manufaktur DFM","desain untuk assembly DFA","sustainability desain","ecodesign cradle-to-cradle","biobased material","desain emosi kansei","sensory design","desain pengalaman produk","UI UX produk fisik connected","IoT connected product","wearable desain","furniture desain","packaging desain sustainable","branding produk FMCG","desain budaya lokal","kearifan lokal material","rotan bambu desain","kerajinan tangan inovasi","desain transportasi otomotif","interior automotive design","design thinking process","design brief brief analysis","user research ethnographic","usability testing produk","desain inklusif disabilitas","desain anak-anak toy","desain medis alat bantu","smart product IoT","product lifecycle management PLM","hak cipta desain industri","patent produk","kompetisi Red Dot iF Award","desain UMKM branding","design for social impact"]
  },
  {
    id: "seni-rupa", name: "Seni Rupa & Kriya", faculty: "Seni, Desain & Media",
    keywords: ["seni rupa kontemporer","lukisan media campuran","seni instalasi site-specific","performance art","video art","net art digital","seni digital","generative art coding","AI art Midjourney Stable","seni pahat patung","keramik tembikar","kriya tekstil batik","ikat tenun Nusantara","wastra Nusantara","ecoprint natural dye","kriya kayu ukiran","kerajinan logam tembaga","seni grafis cetak","serigraphy sablon","fotografi seni dokumenter","fotografi jalanan street","foto jurnalistik","kurator seni","manajemen galeri","museum studies kuratorial","harga karya seni","art market Indonesia","art fair ARTJOG","ArtMoments Jakarta","NFT art marketplace","OpenSea Foundation NFT","tokenisasi karya seni","residensi seniman","hibah seni","arts entrepreneurship","seni komunitas socially engaged","socially engaged art","art therapy","seni pendidikan","pedagogi seni","kritik seni","estetika","semiotika visual","postmodernisme seni","seni Islam kaligrafi","seni batik kontemporer","seni Papua suku","seni Bali tradisi","seni Jawa wayang","craft design heritage","collaborative art practice"]
  },
  {
    id: "broadcasting", name: "Broadcasting & Penyiaran", faculty: "Seni, Desain & Media",
    keywords: ["jurnalisme penyiaran","produksi berita TV","anchor presenter skill","reporter lapangan","kamera broadcasting ENG","teknik audio video","color grading correction","sound mixing mastering","editing non-linear Premiere","studio televisi virtual","green screen keying","live streaming OB van","satellite uplink","transmisi penyiaran","frekuensi spektrum alokasi","regulasi KPI","izin siaran IPP","TV digital DVB-T2 ASO","radio digital DAB+","podcast audio","podcast video","streaming platform OTT","Netflix konten lokal","konten kreator monetisasi","YouTube SEO","TikTok algorithm","Instagram Reels","short form video","influencer economy","talent management artis","program development format","format TV reality show","talk show","infotainment regulasi","berita hoaks verifikasi","news gathering OSINT","investigative journalism","media ownership Indonesia","TVRI RRI publik","media etika kode","Dewan Pers","jurnalisme data","komputasi jurnalisme","AR VR broadcasting","hologram siaran","AI content generasi","social media listening","audience measurement Nielsen","clickbait sensasionalisme","citizen journalism ethics"]
  },

  // === PERTANIAN & SUMBER DAYA === (8)
  {
    id: "agroteknologi", name: "Agroteknologi", faculty: "Pertanian & Sumber Daya",
    keywords: ["tanaman pangan","budidaya padi","jagung kedelai","hortikultura","perkebunan kelapa sawit","karet kakao","pupuk pemupukan","pestisida biopestisida","pengendalian hama terpadu","irigasi tetes","greenhouse hidroponik","vertical farming","smart agriculture","sensor IoT tanaman","drone pertanian","precision farming","tanah dan kesuburan","kompos organik","biofertilizer","benih unggul varietas","GMO tanaman rekayasa","CRISPR tanaman","food security ketahanan","perubahan iklim pertanian","adaptasi tanaman","ketahanan pangan nasional","BULOG cadangan","pangan lokal diversifikasi","sistem pertanian agroforestri","sertifikasi organik","soil health microbiome","rhizosphere dinamik","mycorrhizae mutualism","nitrogen fixation biological","cover crop benefits","regenerative agriculture prinsip","agroekologi tradisional","indigenous farming knowledge","carbon farming kredit","food forest system","permaculture design","terrace farming erosion","biochar soil amendment","phosphorus cycling management","micro-irrigation precision","data pertanian digital farm","Satelit LAPAN peta pertanian","kebijakan pertanian pemerintah","vertical integration agro","farm to fork traceability"]
  },
  {
    id: "peternakan", name: "Peternakan", faculty: "Pertanian & Sumber Daya",
    keywords: ["produksi ternak sapi","ayam broiler petelur","babi kambing domba","nutrisi ternak","pakan formula","manajemen kandang","biosekuriti","penyakit hewan","vaksin ternak","antibiotik alternatives","zoonosis one health","susu sapi perah","daging sapi impor","industri ayam nasional","UMKM peternakan","cold chain daging","sertifikasi halal ternak","RPH modern","manure management","biogas kotoran","inseminasi buatan","embryo transfer","genomik ternak","precision livestock","wearable ternak","produktivitas unggas","swasembada daging","impor sapi Australia","peternakan intensif","animal welfare","precision livestock feeding","body condition scoring","genomic selection breeding","BLUP estimated breeding value","AI artificial insemination modern","ovum pick up OPU","embryo cryopreservation","sexed semen technology","gene editing livestock","cellular agriculture cultivated","fermented feed silage","total mixed ration TMR","methane reduction enteric","pasture carbon sequestration","welfare audit animal","five freedoms animal welfare","hewan kurban traceability","blockchain ternak ID","halal slaughter certification","nutraceutical feed additive"]
  },
  {
    id: "kehutanan", name: "Kehutanan", faculty: "Pertanian & Sumber Daya",
    keywords: ["pengelolaan hutan","deforestasi Indonesia","REDD+ karbon hutan","perhutanan sosial","hutan kemasyarakatan","hutan adat","konservasi biodiversitas","taman nasional","KLHK kebijakan","moratorium sawit","sertifikasi FSC","SVLK kayu","kayu olahan ekspor","biomassa energi","reforestasi penghijauan","agroforestri NTFP","rotan bambu","damar getah","silvofishery mangrove","restorasi gambut","BRGM","kebakaran hutan asap","hotspot monitoring","carbon credit voluntary","nature-based solution","green bond kehutanan","ekowisata","jasa lingkungan","forest governance","illegal logging pemberantasan","forest carbon market","voluntary carbon standard VCS","gold standard forest","REDD+ MRV measurement","remote sensing deforestation","GFW global forest watch","lidar forest inventory","UAV drone hutan","agroforestry carbon sequestration","community forest enterprise","non-timber forest economic","hukum kehutanan UU Cipta","timber legality SVLK","illegal logging enforcement","wildlife crime perdagangan satwa","satwa liar perlindungan","CITES appendix","orangutan habitat conservation","forest landscape restoration","payments ecosystem services PES"]
  },
  {
    id: "perikanan", name: "Perikanan", faculty: "Pertanian & Sumber Daya",
    keywords: ["perikanan tangkap","perikanan budidaya","akuakultur intensif","udang vaname","bandeng","nila tilapia","lele catfish","ikan hias ekspor","budidaya rumput laut","kerang tiram","lobster value chain","cold storage rantai dingin","sertifikasi MSC","illegal fishing IUU","penangkapan terukur KKP","overfishing stok ikan","coral reef restoration","mangrove silvofishery","blue economy","ocean governance","CCRF FAO","ekspor perikanan","pengolahan fillet","HACCP food safety","rantai nilai produk laut","pelabuhan perikanan","kapal nelayan subsidi","asuransi nelayan","koperasi nelayan","digitalisasi perikanan","aquatic monitoring ecosystem","coral bleaching restoration","marine spatial planning","blue carbon kelp seagrass","carbon sequestration laut","marine protected area MPA","deep sea fishery","small-scale fisheries SSF","gender in fisheries","perempuan nelayan","e-logbook tangkapan","vessel monitoring system VMS","AIS automatic identification","fish aggregating device FAD","bycatch reduction device","shark fin ban","aquaculture biosecurity","fish welfare","traceability blockchain perikanan","ecosystem approach fisheries"]
  },
  {
    id: "teknologi-pangan", name: "Teknologi Pangan", faculty: "Pertanian & Sumber Daya",
    keywords: ["pengolahan pangan","keamanan pangan BPOM","HACCP ISO 22000","uji organoleptik","formulasi produk","pengawet alami","teknologi fermentasi","pangan fungsional","nutraceutical","fortifikasi pangan","kemasan aktif","modified atmosphere","freeze drying","teknologi ekstrusi","UHT suhu tinggi","novel protein","alternative protein","plant-based meat","cultivated meat","serangga protein","food waste reduction","zero waste pangan","clean label","free from additives","halal food chain","jaminan halal","distribusi cold chain","startup foodtech","food innovation","pangan lokal sagu singkong","precision fermentation protein","mycoprotein fungi production","insect protein processing","algae extraction astaxanthin","functional ingredient bioactive","polyphenol extraction","antioxidant bioavailability","probiotics health claims","synbiotic product","fiber enrichment bread","sugar reduction reformulation","sensory evaluation panel","consumer acceptance test","food system sustainability","food loss supply chain","carbon footprint pangan","packaging biodegradable","fermented food tempeh","food safety regulation CODEX","food labeling digital QR"]
  },
  {
    id: "agribisnis", name: "Agribisnis", faculty: "Pertanian & Sumber Daya",
    keywords: ["manajemen agribisnis","sistem agribisnis","value chain pertanian","supply chain pangan","analisis usahatani","biaya produksi pertanian","harga komoditas analisis","kelayakan investasi pertanian","manajemen risiko pertanian","asuransi usahatani AUTP","pemasaran pertanian","rantai nilai hortikultura","koperasi pertanian","BUMD pertanian","kelembagaan petani GAPOKTAN","penyuluhan pertanian","kemitraan perusahaan","contract farming","off-taker agreement","ekspor pertanian organik","sertifikasi global GAP","perdagangan komoditas sawit","harga tandan buah segar CPO","karet SIR ekspor","kakao fermentasi specialty","kopi specialty Indonesia","beras premium organik","sayur organik lokal","pasar modern peritel","cold chain hortikultura","e-commerce tani digital","pertanian digital marketplace","HKTI petani","KPPU persaingan harga","subsidi pupuk KUR","food sovereignty","ketahanan pangan wilayah","SDGs pertanian zero hunger","pertanian berkelanjutan","agroecology regenerative","fintech pertanian","crowdfunding usahatani","data analytics pertanian","AI prediksi panen","precision agriculture","agribisnis halal","pasar ekspor ASEAN China","food estate nasional","diversifikasi komoditas","value added pangan"]
  },
  {
    id: "teknik-pertanian", name: "Teknik Pertanian", faculty: "Pertanian & Sumber Daya",
    keywords: ["mesin pertanian traktor","transplanter padi mekanik","combine harvester pemanen","thresher pemipil jagung","alat tanam presisi seeder","irigasi tetes drip","sprinkler sistem irigasi","irigasi mikro sprinkler","pompa air pertanian","embung tampungan air","greenhouse otomasi kontrol","climate control greenhouse","nutrisi hidroponik EC pH","aeroponik vertical farm","aquaponik ikan sayur","sensor tanah IoT kelembapan","soil moisture sensor LoRa","weather station pertanian","drone spraying pertanian","drone pemetaan NDVI NDWI","precision farming GPS variable","variable rate application VRA","robot pertanian autonomous","harvest robot picking","sorting grading otomasi AI","post harvest handling panen","cold storage pertanian","penyimpanan biji-bijian silo","grain silo management","energy pertanian solar off-grid","biogas limbah pertanian","mesin pengolahan hasil olahan","RMU rice milling unit","mesin pengering dryer grain","pascapanen kopi wet dry hulling","olahan kakao mesin fermentasi","press minyak kelapa virgin","mesin penyulingan minyak atsiri","dehydrator pengering vakum","pengolahan tepung singkong","mesin packaging labeling","quality control otomatis vision","MFRD mekanisasi pertanian","standar SNI mesin pertanian","K3 mesin pertanian safety","pemeliharaan preventive maintenance","teknologi 4.0 pertanian","elektifikasi pertanian rural","smart irrigation management","telemetry pertanian IoT"]
  },
  {
    id: "akuakultur", name: "Budidaya Perairan (Akuakultur)", faculty: "Pertanian & Sumber Daya",
    keywords: ["akuakultur intensif semi intensif","sistem RAS recirculating aquaculture","bioflok teknologi","IMTA integrated multi trophic","udang vaname L. vannamei","udang windu monodon","ikan nila tilapia","lele channel catfish","mas koi","bawal bintang","kerapu grouper","kakap putih seabass","patin pangasius","lobster air tawar","sidat eel","rumput laut Eucheuma","spirulina microalgae","abalone tiram mutiara","pembibitan hatchery","pemijahan spawning","larval rearing","pakan buatan formula FCR","nutrisi ikan protein lemak","manajemen kualitas air parameter","DO oksigen terlarut","pH amonia nitrit","filter biologis biofilter","probiotik akuakultur","prebiotik immunostimulant","vaksin ikan WSSV","penyakit ikan white spot WSSV","aeromonas VHS penanganan","CBIB cara benih ikan baik","sertifikasi ASC MSC","pembenihan domestik","ekspor udang fillet frozen","cold chain perikanan","HACCP olahan ikan","pengolahan surimi","diversifikasi produk aquaculture","nilai tambah produk laut","digital monitoring akuakultur","sensor kualitas air IoT","AI prediksi penyakit","drone monitoring tambak","aquaponics sistem","shrimp pond management","fish nutrition feed formulation","water quality management"]
  },

  // === PENDIDIKAN & SOSIAL LAIN === (12)
  {
    id: "administrasi-negara", name: "Administrasi Negara", faculty: "Pendidikan & Sosial Lain",
    keywords: ["kebijakan publik","analisis kebijakan","good governance","new public management","birokrasi Weber","reformasi birokrasi","pelayanan publik","standar pelayanan minimal","e-government","SPBE sistem pemerintahan","open government","transparency international","keterbukaan informasi","PPID pejabat","ombudsman RI","mal pelayanan publik","pengadaan LKPP","e-procurement","APBD APBN","akuntabilitas kinerja","SAKIP LAKIP","KPPU persaingan","regulasi impact assessment","desentralisasi asimetris","otonomi khusus","kapasitas daerah","inovasi daerah","smart city governance","SDM ASN","meritokrasi birokrasi","neo-Weberian state","post-NPM governance","collaborative governance","co-production public service","participatory governance","digital government maturity","AI in government","algorithmic decision making","automated benefit determination","open data government","smart regulation","regulatory sandbox","government innovation lab","GovTech startup","civic hackathon","crowdsourcing policy","citizen lab","human-centered public service","service design government","evidence-based policy","public sector innovation"]
  },
  {
    id: "k3", name: "Kesehatan & Keselamatan Kerja (K3)", faculty: "Pendidikan & Sosial Lain",
    keywords: ["identifikasi bahaya","HIRARC penilaian risiko","JSA job safety analysis","APD alat pelindung","kecelakaan kerja","investigasi insiden","near miss reporting","safety culture","behavioral safety","safety leadership","SMK3 OHSAS 45001","ISO 45001","audit K3","inspeksi tempat kerja","BPJS Ketenagakerjaan","kompensasi kecelakaan","penyakit akibat kerja","PAK diagnosis","ergonomi kerja","manual handling","noise vibration exposure","chemical hazard MSDS","fire safety protection","emergency response plan","BCP BCM","industri migas K3 offshore","konstruksi K3 scaffolding","pertambangan safety","kesehatan jiwa pekerja","workplace wellbeing","psychological safety dan K3","wellbeing at work program","organizational trauma","critical incident stress","violence at work","worker health surveillance","occupational epidemiology","health risk assessment OHS","ALARP principle","inherently safer design","process safety management PSM","HAZOP teknik kimia","Bow-tie analysis barrier","fault tree event tree","management of change MOC","contractor safety management","multi-employer worksite","ISO 45001:2018 implementasi","auditor K3 competency","system safety STAMP","human factors engineering"]
  },
  {
    id: "kriminologi", name: "Kriminologi", faculty: "Pendidikan & Sosial Lain",
    keywords: ["teori kriminologi","kejahatan dan penyimpangan","victimologi","korban kejahatan","hukum pidana","sistem peradilan","kepolisian Polri","jaksa penuntut","hakim pengadilan","lembaga pemasyarakatan","restorative justice","rehabilitasi narapidana","recidivism pencegahan","kejahatan terorganisir","korupsi pemberantasan","narkoba jaringan","human trafficking","cybercrime siber","dark web","money laundering","terorisme radikalisasi","deradikalisasi BNPT","kejahatan lingkungan","white collar crime","gender based violence","KDRT kekerasan","child abuse","kejahatan digital AI","forensik digital","profiling kriminal","kriminologi budaya","crime and popular culture","media dan kejahatan","fear of crime","victimization survey","NCVS national crime","restorative justice program","truth and reconciliation","transitional justice","war crime tribunal ICC","international criminal law","genocide studies","terrorism prevention","counter radicalization P/CVE","digital forensics mobile","blockchain evidence","AI predictive policing","crime mapping GIS","procedural justice police","policing legitimacy community","reintegration narapidana"]
  },
  {
    id: "gizi", name: "Gizi", faculty: "Pendidikan & Sosial Lain",
    keywords: ["nutrisi makronutrien","protein karbohidrat lemak","vitamin mineral","kebutuhan gizi harian","gizi anak balita","stunting wasting","gizi ibu hamil","laktasi ASI","gizi remaja","gizi lansia","gizi atlet olahraga","diet penyakit kronik","diet diabetes","diet hipertensi","diet kanker","gut microbiome","intermittent fasting","plant-based diet","Mediterranean diet","food label membaca","URT ukuran rumah tangga","recall 24 jam","food frequency questionnaire","nutrisurvey","Nutrifit","intervensi gizi komunitas","posyandu","PMT tambahan","fortifikasi pangan","kebijakan gizi nasional","nutrigenomik genetik","metabolomik gizi","microbiome diet interaction","personalized nutrition AI","digital food diary app","diet tracking application","wearable metabolic monitor","continuous glucose monitor","nutri-epigenetics","clock gene chrono-nutrition","keto diet evidence-based","vegan nutrition Indonesia","soy tempeh isoflavone","probiotik kedelai","gizi dan imunitas","gizi infeksi malnutrisi","micronutrient deficiency Indonesia","peta kerawanan pangan","gizi bencana darurat","health promotion gizi","nutritional epidemiology"]
  },
  {
    id: "pwk", name: "Perencanaan Wilayah & Kota", faculty: "Pendidikan & Sosial Lain",
    keywords: ["tata ruang wilayah","RTRW nasional","RDTR detail","perencanaan kota","urban design","land use planning","GIS spasial","remote sensing","ArcGIS QGIS","kawasan industri","kawasan ekonomi khusus KEK","IKN ibu kota nusantara","smart city","kota layak huni","transportasi publik","TOD transit oriented","ruang terbuka hijau RTH","banjir mitigasi","drainase kota","kumuh slum upgrading","perumahan terjangkau","fasilitas sosial","infrastruktur kota","sumber daya air","agglomeration ekonomi","metropolitan manajemen","RDTR berbasis data","partisipasi masyarakat perencanaan","urban metabolism analysis","material flow kota","urban mining","urban microclimate","cool island effect","biodiversity urban planning","greenway planning","urban food system","food desert mapping","compact city theory","new urbanism","15-minute city","walkability score","bikeable city infrastructure","shared mobility planning","autonomous vehicle planning","urban sensing data","real-time city monitoring","digital urban planning BIM","urban resilience disaster","housing affordability index","transit demand modeling","smart land management"]
  },
  {
    id: "bk", name: "Bimbingan & Konseling", faculty: "Pendidikan & Sosial Lain",
    keywords: ["teori konseling","pendekatan psikoanalitik Freud","behavioral therapy","CBT kognitif perilaku","humanistik Rogers","Gestalt therapy","solution-focused brief therapy","narrative therapy","konseling kelompok","konseling individu","konseling karir","konseling pernikahan keluarga","konseling trauma","konseling krisis","konseling remaja","konseling anak","konseling dewasa","konseling lansia","asesmen psikologis WISC MMPI","konseling sekolah","BK di kurikulum Merdeka","program preventif promotif","layanan responsif BK","perencanaan individual","kolaborasi guru BK","supervisi konseling","etika konseling ABKIN","kode etik konselor","konseling berbasis bukti","riset konseling","peer counseling","school-based mental health","wellbeing siswa","bully penanganan","NAPZA pencegahan","orientasi seksual gender","konseling inklusif difabel","trauma informed care","resilience building","karakter dan nilai","emotional intelligence","konseling online digital","aplikasi wellbeing mental","mindfulness sekolah","parent counseling","kekerasan seksual konseling","stress akademik mahasiswa","university counseling centre","ACT acceptance commitment","motivational interviewing","positive behavior support"]
  },
  {
    id: "pendidikan-bahasa-inggris", name: "Pendidikan Bahasa Inggris", faculty: "Pendidikan & Sosial Lain",
    keywords: ["linguistics applied","SLA second language acquisition","krashen input hypothesis","communicative language teaching CLT","task-based language teaching TBLT","content language integrated learning CLIL","bilingual education","English academic purposes EAP","English specific purposes ESP","skills 4 LSRW","listening comprehension","speaking fluency","reading strategies","writing academic","IELTS preparation","TOEFL iBT","Cambridge CEFR level","authentic material","technology-enhanced language learning CALL","online learning platform","Duolingo gamifikasi","AI chatbot language tutor","pronunciation phonology","phonetics articulation","intonation stress patterns","grammar functional","discourse analysis","pragmatics cross-cultural communication","translation interpreting","contrastive analysis","error analysis","corpus linguistics","lexicography vocabulary","materials development","syllabus design","lesson plan preparation","microteaching praktik","classroom management EFL","peer teaching feedback","reflective teaching portfolio","assessment literasi bahasa","teacher cognition","teacher professional development","MGMP bahasa Inggris","kurikulum Merdeka mapel bahasa","journal TEFLIN","penelitian tindakan kelas PTK","global English trend","World Englishes","language policy Indonesia"]
  },
  {
    id: "pekerjaan-sosial", name: "Pekerjaan Sosial", faculty: "Pendidikan & Sosial Lain",
    keywords: ["teori pekerjaan sosial","perspektif sistem ekologi","strengths-based approach","empowerment model","community development","pengorganisasian masyarakat","advokasi kebijakan sosial","analisis kebijakan kesejahteraan","DTKS data sosial","PKH program keluarga harapan","BPNT sembako","bansos regulasi Kemensos","lansia vulnerable","difabel disabilitas","anak terlantar","korban KDRT","trafficking survivor","kemiskinan intervensi","gerakan sosial","capacity building komunitas","participatory rural appraisal","village assessment","kepemimpinan lokal","modal sosial","gotong royong","rumah singgah","panti asuhan LKSA","standar LKSA akreditasi sosial","pekerja sosial profesional PEKSOS","PSKS potensi sumber kesejahteraan","CSR perusahaan strategis","philanthropy strategic","social enterprise","dampak sosial measurement","social return on investment SROI","SDGs kemiskinan setara gender","social work international IFSW","NASW standard","evidence-based social work","riset sosial kualitatif","ethnographic research community","community-based participatory research","pekerja sosial di rumah sakit","medis sosial","mental health social worker","disaster social work","pekerja sosial sekolah","substance abuse counseling","child welfare protection","restorative community practice"]
  },
  {
    id: "paud", name: "PAUD (Pendidikan Anak Usia Dini)", faculty: "Pendidikan & Sosial Lain",
    keywords: ["perkembangan anak 0-6 tahun","teori Piaget sensorimotor","Vygotsky prasekolah","Erikson tahap psikososial","perkembangan kognitif anak","perkembangan bahasa anak","perkembangan motorik halus kasar","perkembangan sosial emosional","STPPA standar tingkat pencapaian","Kurikulum PAUD Merdeka","bermain sebagai belajar","pendekatan Montessori","Reggio Emilia approach","bermain bebas unstructured play","STEM untuk anak","literasi dini membaca menulis","numerasi dini","seni kreativitas anak","musik gerak anak","dongeng storytelling","pola asuh parenting positif","attachment teori Bowlby","responsive caregiving","rutinitas dan batas anak","tantrum manajemen","anak berkebutuhan khusus dini","deteksi tumbuh kembang","KPSP skrining","stimulasi 1000 HPK","ASI gizi anak","imunisasi jadwal","posyandu balita","TK KB SPS RA","Permendikbud 146 2014","akreditasi lembaga PAUD","kurikulum berbasis komunitas","parenting education","PAUD holistik integratif","layanan terpadu PAUD HI","tenaga pendidik PAUD","kompetensi guru TK","sertifikasi pendidik anak","program PAUD Indonesia","PAUD digital teknologi","anak dan screen time","kekerasan pada anak perlindungan","kekerasan seksual anak deteksi","child-centered approach","play-based assessment","transdisciplinary early childhood"]
  },
  {
    id: "manajemen-pendidikan", name: "Manajemen Pendidikan", faculty: "Pendidikan & Sosial Lain",
    keywords: ["manajemen sekolah","kepala sekolah leadership","visi misi sekolah","rencana kerja sekolah","RKAS anggaran sekolah","manajemen kelas","manajemen kurikulum","manajemen kesiswaan","manajemen SDM pendidikan","rekrutmen guru","pengembangan profesional guru","supervisi pendidikan","akreditasi BAN-S/M","Rapor Pendidikan","asesmen nasional ANBK","AN AKM literasi numerasi","profil pelajar Pancasila","gerakan sekolah menyenangkan","transformasi sekolah","kepemimpinan instruksional","coaching kepala sekolah","manajemen perguruan tinggi","OTK universitas","statuta PT","akreditasi BAN-PT","akreditasi internasional AACSB","tata kelola universitas","remunerasi dosen","BOPTN anggaran","riset universitas","DIKTI kebijakan","kampus Merdeka Belajar","kurikulum MBKM","kemitraan industri kampus","teaching factory","manajemen mutu pendidikan ISO","leadership distributed","school improvement","pembiayaan pendidikan BOS","beasiswa KIP-K","PPDB sistem zonasi","manajemen data pendidikan Dapodik","sistem informasi sekolah","literasi digital sekolah","green school","well-being sekolah","transformational school leadership","educational policy analysis","school culture climate","talent management guru","teacher appraisal performance"]
  },
  {
    id: "pendidikan-bahasa-indonesia", name: "Pendidikan Bahasa Indonesia", faculty: "Pendidikan & Sosial Lain",
    keywords: ["linguistik Indonesia","fonologi bahasa Indonesia","morfologi kata","sintaksis kalimat","semantik makna","pragmatik konteks","wacana analisis","bahasa dan budaya","dialek bahasa Jawa Sunda","bahasa daerah Indonesia","KBBI revisi","EYD PUEBI ejaan","tata bahasa baku","pembelajaran bahasa Indonesia","keterampilan berbicara","keterampilan menulis","keterampilan membaca","keterampilan menyimak","sastra sebagai media belajar","puisi cerpen novel","apresiasi sastra","kajian sastra angkatan","sastra lama pantun syair","sastra populer digital","membaca kritis","literasi kritis","media literasi","menulis kreatif","jurnalisme bahasa","penulisan akademik","plagiarisme akademik","tata tulis karya ilmiah","Penelitian Tindakan Kelas PTK","model pembelajaran teks","teks eksposisi argumentasi","teks narasi deskripsi","kurikulum Merdeka bahasa Indonesia","asesmen literasi membaca","PISA membaca","tes ANBK literasi","bahasa Indonesia global PBB","penerjemahan bahasa asing","bahasa ASEAN Indonesia","bahasa Indonesia diaspora","bahasa digital media sosial","bahasa hukum juridis","bahasa media massa","NLP bahasa Indonesia AI","corpus bahasa Indonesia","multilingual Indonesia","bahasa isyarat SIBI"]
  },
  {
    id: "teknologi-pendidikan", name: "Teknologi Pendidikan", faculty: "Pendidikan & Sosial Lain",
    keywords: ["desain instruksional","ADDIE model","SAM successive approximation","backward design Wiggins","learning objectives","bloom taxonomy revisi","constructivism learning theory","connectivism Siemens","online learning e-learning","synchronous asynchronous","LMS Moodle Google Classroom","Canvas Schoology","massive open online course MOOC","microlearning","mobile learning m-learning","gamifikasi pendidikan","game-based learning","serious game","augmented reality AR pendidikan","virtual reality VR simulasi","mixed reality MR","AI tutoring intelligent","adaptive learning sistem","personalized learning path","learning analytics data","educational data mining","kecerdasan buatan pendidikan","flipped classroom","project based learning teknologi","STEM STEAM","coding computational thinking","robotika di sekolah","3D printing pendidikan","video pembelajaran produksi","podcast edukasi","infografis animasi pendidikan","aksesibilitas difabel teknologi","UDL universal design learning","learning disability teknologi","evaluasi teknologi pendidikan","evidence-based EdTech","ROI program training","corporate learning development","instructional designer karir","multimedia interaktif","moodle development","scorm xAPI","Padlet Mentimeter Kahoot","kebijakan teknologi pendidikan","teacher digital competency","digital equity access"]
  },
]
